
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-25T09:49:17.892+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Doctor",
                      portName = "DoctorHttpPost",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "https://preproduction.newcropaccounts.com/v7/WebServices/Doctor.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.DoctorHttpPost")
                      
public class DoctorHttpPostImpl implements DoctorHttpPost {

    private static final Logger LOG = Logger.getLogger(DoctorHttpPostImpl.class.getName());

}
