package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-25T09:49:17.892+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "DoctorSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DoctorSoap {

    /**
     * Returns the registration status for all Licensed Prescriber for a given Account ID / Site ID.
     */
    @WebResult(name = "AllLicensedPrescribersStatusResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "AllLicensedPrescribersStatus", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.AllLicensedPrescribersStatus")
    @WebMethod(operationName = "AllLicensedPrescribersStatus", action = "https://secure.newcropaccounts.com/V7/webservices/AllLicensedPrescribersStatus")
    @ResponseWrapper(localName = "AllLicensedPrescribersStatusResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.AllLicensedPrescribersStatusResponse")
    public https.secure_newcropaccounts_com.v7.webservices.RegisterPrescriberDetailResult allLicensedPrescribersStatus(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest
    );

    /**
     * Registers an identifier for a Licensed Prescriber.
     */
    @WebResult(name = "RegisterLicensedPrescriberIdentifierResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "RegisterLicensedPrescriberIdentifier", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.RegisterLicensedPrescriberIdentifier")
    @WebMethod(operationName = "RegisterLicensedPrescriberIdentifier", action = "https://secure.newcropaccounts.com/V7/webservices/RegisterLicensedPrescriberIdentifier")
    @ResponseWrapper(localName = "RegisterLicensedPrescriberIdentifierResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.RegisterLicensedPrescriberIdentifierResponse")
    public https.secure_newcropaccounts_com.v7.webservices.Result registerLicensedPrescriberIdentifier(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "identifier", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String identifier,
        @WebParam(name = "identifierType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String identifierType,
        @WebParam(name = "status", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String status,
        @WebParam(name = "expirationDate", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String expirationDate
    );

    /**
     * Returns the registration status of a Licensed Prescriber.
     */
    @WebResult(name = "LicensedPrescriberStatusResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "LicensedPrescriberStatus", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.LicensedPrescriberStatus")
    @WebMethod(operationName = "LicensedPrescriberStatus", action = "https://secure.newcropaccounts.com/V7/webservices/LicensedPrescriberStatus")
    @ResponseWrapper(localName = "LicensedPrescriberStatusResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.LicensedPrescriberStatusResponse")
    public https.secure_newcropaccounts_com.v7.webservices.RegisterPrescriberDetailResult licensedPrescriberStatus(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "licensedPrescriberID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String licensedPrescriberID,
        @WebParam(name = "locationID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationID
    );

    /**
     * Registers a Licensed Prescriber.
     */
    @WebResult(name = "RegisterLicensedPrescriberResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "RegisterLicensedPrescriber", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.RegisterLicensedPrescriber")
    @WebMethod(operationName = "RegisterLicensedPrescriber", action = "https://secure.newcropaccounts.com/V7/webservices/RegisterLicensedPrescriber")
    @ResponseWrapper(localName = "RegisterLicensedPrescriberResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.RegisterLicensedPrescriberResponse")
    public https.secure_newcropaccounts_com.v7.webservices.RegisterPrescriberDetailResult registerLicensedPrescriber(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "xmlIn", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String xmlIn
    );
}
