package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-25T16:48:50.956+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "DrugSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DrugSoap {

    /**
     * Searches for information regarding drug/drug interactions based on current and proposed medications.
     */
    @WebResult(name = "DrugDrugInteractionV2Result", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugDrugInteractionV2", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugDrugInteractionV2")
    @WebMethod(operationName = "DrugDrugInteractionV2", action = "https://secure.newcropaccounts.com/V7/webservices/DrugDrugInteractionV2")
    @ResponseWrapper(localName = "DrugDrugInteractionV2Response", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugDrugInteractionV2Response")
    public https.secure_newcropaccounts_com.v7.webservices.DrugInteractionResult drugDrugInteractionV2(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "currentMedications", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString currentMedications,
        @WebParam(name = "proposedMedications", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType,
        @WebParam(name = "severityExclusionMask", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        int severityExclusionMask
    );

    /**
     * Returns a list of food interactions for a given drug concept.
     */
    @WebResult(name = "DrugFoodInteractionResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugFoodInteraction", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugFoodInteraction")
    @WebMethod(operationName = "DrugFoodInteraction", action = "https://secure.newcropaccounts.com/V7/webservices/DrugFoodInteraction")
    @ResponseWrapper(localName = "DrugFoodInteractionResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugFoodInteractionResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugFoodDetailResult drugFoodInteraction(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "drugId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugId,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType
    );

    /**
     * Retrieves a list of drugs for a diagnosis list
     */
    @WebResult(name = "DrugsByDiagnosisResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugsByDiagnosis", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugsByDiagnosis")
    @WebMethod(operationName = "DrugsByDiagnosis", action = "https://secure.newcropaccounts.com/V7/webservices/DrugsByDiagnosis")
    @ResponseWrapper(localName = "DrugsByDiagnosisResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugsByDiagnosisResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugDetailResult drugsByDiagnosis(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "diagnosisList", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString diagnosisList,
        @WebParam(name = "diagnosisListType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String diagnosisListType
    );

    /**
     * Searches for drug information based on the name of the drug.
     */
    @WebResult(name = "DrugSearchResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugSearch", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugSearch")
    @WebMethod(operationName = "DrugSearch", action = "https://secure.newcropaccounts.com/V7/webservices/DrugSearch")
    @ResponseWrapper(localName = "DrugSearchResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugSearchResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugDetailResult drugSearch(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "drugName", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugName,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType,
        @WebParam(name = "includeObsolete", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeObsolete,
        @WebParam(name = "searchBrandGeneric", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchBrandGeneric,
        @WebParam(name = "searchRxOTC", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchRxOTC,
        @WebParam(name = "searchDrugSupply", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchDrugSupply
    );

    /**
     * Add/deletes to a provider's drug favorites list.
     */
    @WebResult(name = "MaintainProviderDrugFavoritesResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "MaintainProviderDrugFavorites", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.MaintainProviderDrugFavorites")
    @WebMethod(operationName = "MaintainProviderDrugFavorites", action = "https://secure.newcropaccounts.com/V7/webservices/MaintainProviderDrugFavorites")
    @ResponseWrapper(localName = "MaintainProviderDrugFavoritesResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.MaintainProviderDrugFavoritesResponse")
    public https.secure_newcropaccounts_com.v7.webservices.Result maintainProviderDrugFavorites(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "locationId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationId,
        @WebParam(name = "providerId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String providerId,
        @WebParam(name = "drugId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugId,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType,
        @WebParam(name = "actionCode", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String actionCode
    );

    /**
     * Searches for drug information based on the name of the drug.  Also returns formulary coverage information.
     */
    @WebResult(name = "DrugSearchWithFormularyWithFavoritesResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugSearchWithFormularyWithFavorites", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugSearchWithFormularyWithFavorites")
    @WebMethod(operationName = "DrugSearchWithFormularyWithFavorites", action = "https://secure.newcropaccounts.com/V7/webservices/DrugSearchWithFormularyWithFavorites")
    @ResponseWrapper(localName = "DrugSearchWithFormularyWithFavoritesResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugSearchWithFormularyWithFavoritesResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyFavoriteDetailResult drugSearchWithFormularyWithFavorites(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "healthplanID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanID,
        @WebParam(name = "healthplanTypeID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanTypeID,
        @WebParam(name = "drugName", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugName,
        @WebParam(name = "includeObsolete", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeObsolete,
        @WebParam(name = "searchBrandGeneric", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchBrandGeneric,
        @WebParam(name = "searchRxOTC", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchRxOTC,
        @WebParam(name = "searchDrugSupply", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchDrugSupply,
        @WebParam(name = "locationId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationId,
        @WebParam(name = "providerId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String providerId
    );

    /**
     * Retrieves a list of drugs for a diagnosis list with formulary coverage
     */
    @WebResult(name = "DrugsByDiagnosisWithFormularyResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugsByDiagnosisWithFormulary", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugsByDiagnosisWithFormulary")
    @WebMethod(operationName = "DrugsByDiagnosisWithFormulary", action = "https://secure.newcropaccounts.com/V7/webservices/DrugsByDiagnosisWithFormulary")
    @ResponseWrapper(localName = "DrugsByDiagnosisWithFormularyResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugsByDiagnosisWithFormularyResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult drugsByDiagnosisWithFormulary(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "healthplanID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanID,
        @WebParam(name = "healthplanTypeID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanTypeID,
        @WebParam(name = "diagnosisList", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString diagnosisList,
        @WebParam(name = "diagnosisListType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String diagnosisListType
    );

    /**
     * Returns drug packaging for a given drug concept.
     */
    @WebResult(name = "DrugPackageDetailsResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugPackageDetails", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugPackageDetails")
    @WebMethod(operationName = "DrugPackageDetails", action = "https://secure.newcropaccounts.com/V7/webservices/DrugPackageDetails")
    @ResponseWrapper(localName = "DrugPackageDetailsResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugPackageDetailsResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugPackageDetailResult drugPackageDetails(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "drugConcept", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConcept,
        @WebParam(name = "drugConceptType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConceptType
    );

    /**
     * Searches for information regarding drug/allergy interactions based on current and proposed medications.
     */
    @WebResult(name = "DrugAllergyInteractionResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugAllergyInteraction", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugAllergyInteraction")
    @WebMethod(operationName = "DrugAllergyInteraction", action = "https://secure.newcropaccounts.com/V7/webservices/DrugAllergyInteraction")
    @ResponseWrapper(localName = "DrugAllergyInteractionResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugAllergyInteractionResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugAllergyDetailResult drugAllergyInteraction(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "allergies", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString allergies,
        @WebParam(name = "proposedMedications", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType
    );

    /**
     * SUPERSEDED - Refer to the NewCrop Drug web services test and description web page for the new method of obtaining drug monographs.
     */
    @WebResult(name = "DrugMonographResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugMonograph", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugMonograph")
    @WebMethod(operationName = "DrugMonograph", action = "https://secure.newcropaccounts.com/V7/webservices/DrugMonograph")
    @ResponseWrapper(localName = "DrugMonographResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugMonographResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugMonographResult drugMonograph(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "drugConcept", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConcept,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType,
        @WebParam(name = "monographFormat", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String monographFormat
    );

    /**
     * Add/deletes to a provider's drug favorites list.
     */
    @WebResult(name = "MaintainProviderDrugFavoritesArrayResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "MaintainProviderDrugFavoritesArray", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.MaintainProviderDrugFavoritesArray")
    @WebMethod(operationName = "MaintainProviderDrugFavoritesArray", action = "https://secure.newcropaccounts.com/V7/webservices/MaintainProviderDrugFavoritesArray")
    @ResponseWrapper(localName = "MaintainProviderDrugFavoritesArrayResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.MaintainProviderDrugFavoritesArrayResponse")
    public https.secure_newcropaccounts_com.v7.webservices.Result maintainProviderDrugFavoritesArray(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "locationId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationId,
        @WebParam(name = "providerId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String providerId,
        @WebParam(name = "drugIds", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString drugIds,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType,
        @WebParam(name = "actionCode", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String actionCode
    );

    /**
     * Returns validation information for a given list of comma separated NDCs.
     */
    @WebResult(name = "ValidateNDCListResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "ValidateNDCList", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.ValidateNDCList")
    @WebMethod(operationName = "ValidateNDCList", action = "https://secure.newcropaccounts.com/V7/webservices/ValidateNDCList")
    @ResponseWrapper(localName = "ValidateNDCListResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.ValidateNDCListResponse")
    public https.secure_newcropaccounts_com.v7.webservices.NDCValidationDetailResult validateNDCList(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "ndcList", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString ndcList,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType
    );

    /**
     * Searches for information regarding drug/drug interactions based on current and proposed medications.
     */
    @WebResult(name = "DrugDrugInteractionResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugDrugInteraction", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugDrugInteraction")
    @WebMethod(operationName = "DrugDrugInteraction", action = "https://secure.newcropaccounts.com/V7/webservices/DrugDrugInteraction")
    @ResponseWrapper(localName = "DrugDrugInteractionResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugDrugInteractionResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugInteractionResult drugDrugInteraction(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "currentMedications", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString currentMedications,
        @WebParam(name = "proposedMedications", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,
        @WebParam(name = "drugStandardType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugStandardType
    );

    /**
     * Searches for drug information based on the name of the drug.  Also returns formulary coverage information.
     */
    @WebResult(name = "DrugSearchWithFormularyResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "DrugSearchWithFormulary", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugSearchWithFormulary")
    @WebMethod(operationName = "DrugSearchWithFormulary", action = "https://secure.newcropaccounts.com/V7/webservices/DrugSearchWithFormulary")
    @ResponseWrapper(localName = "DrugSearchWithFormularyResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.DrugSearchWithFormularyResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult drugSearchWithFormulary(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "healthplanID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanID,
        @WebParam(name = "healthplanTypeID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanTypeID,
        @WebParam(name = "drugName", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugName,
        @WebParam(name = "includeObsolete", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeObsolete,
        @WebParam(name = "searchBrandGeneric", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchBrandGeneric,
        @WebParam(name = "searchRxOTC", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchRxOTC,
        @WebParam(name = "searchDrugSupply", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String searchDrugSupply
    );
}
