
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-25T16:48:50.842+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Drug",
                      portName = "DrugSoap",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "http://preproduction.newcropaccounts.com/V7/WebServices/Drug.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.DrugSoap")
                      
public class DrugSoapImpl implements DrugSoap {

    private static final Logger LOG = Logger.getLogger(DrugSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugDrugInteractionV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  currentMedications ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  proposedMedications ,)java.lang.String  drugStandardType ,)int  severityExclusionMask )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugInteractionResult drugDrugInteractionV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString currentMedications,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,java.lang.String drugStandardType,int severityExclusionMask) { 
        LOG.info("Executing operation drugDrugInteractionV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(currentMedications);
        System.out.println(proposedMedications);
        System.out.println(drugStandardType);
        System.out.println(severityExclusionMask);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugInteractionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugFoodInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  drugId ,)java.lang.String  drugStandardType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugFoodDetailResult drugFoodInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String drugId,java.lang.String drugStandardType) { 
        LOG.info("Executing operation drugFoodInteraction");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(drugId);
        System.out.println(drugStandardType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugFoodDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugsByDiagnosis(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  diagnosisList ,)java.lang.String  diagnosisListType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugDetailResult drugsByDiagnosis(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString diagnosisList,java.lang.String diagnosisListType) { 
        LOG.info("Executing operation drugsByDiagnosis");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(diagnosisList);
        System.out.println(diagnosisListType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugSearch(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  drugName ,)java.lang.String  drugStandardType ,)java.lang.String  includeObsolete ,)java.lang.String  searchBrandGeneric ,)java.lang.String  searchRxOTC ,)java.lang.String  searchDrugSupply )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugDetailResult drugSearch(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String drugName,java.lang.String drugStandardType,java.lang.String includeObsolete,java.lang.String searchBrandGeneric,java.lang.String searchRxOTC,java.lang.String searchDrugSupply) { 
        LOG.info("Executing operation drugSearch");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(drugName);
        System.out.println(drugStandardType);
        System.out.println(includeObsolete);
        System.out.println(searchBrandGeneric);
        System.out.println(searchRxOTC);
        System.out.println(searchDrugSupply);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#maintainProviderDrugFavorites(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  providerId ,)java.lang.String  drugId ,)java.lang.String  drugStandardType ,)java.lang.String  actionCode )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result maintainProviderDrugFavorites(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String providerId,java.lang.String drugId,java.lang.String drugStandardType,java.lang.String actionCode) { 
        LOG.info("Executing operation maintainProviderDrugFavorites");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(providerId);
        System.out.println(drugId);
        System.out.println(drugStandardType);
        System.out.println(actionCode);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugSearchWithFormularyWithFavorites(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  drugName ,)java.lang.String  includeObsolete ,)java.lang.String  searchBrandGeneric ,)java.lang.String  searchRxOTC ,)java.lang.String  searchDrugSupply ,)java.lang.String  locationId ,)java.lang.String  providerId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyFavoriteDetailResult drugSearchWithFormularyWithFavorites(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String drugName,java.lang.String includeObsolete,java.lang.String searchBrandGeneric,java.lang.String searchRxOTC,java.lang.String searchDrugSupply,java.lang.String locationId,java.lang.String providerId) { 
        LOG.info("Executing operation drugSearchWithFormularyWithFavorites");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(drugName);
        System.out.println(includeObsolete);
        System.out.println(searchBrandGeneric);
        System.out.println(searchRxOTC);
        System.out.println(searchDrugSupply);
        System.out.println(locationId);
        System.out.println(providerId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugFormularyFavoriteDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugsByDiagnosisWithFormulary(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  diagnosisList ,)java.lang.String  diagnosisListType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult drugsByDiagnosisWithFormulary(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString diagnosisList,java.lang.String diagnosisListType) { 
        LOG.info("Executing operation drugsByDiagnosisWithFormulary");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(diagnosisList);
        System.out.println(diagnosisListType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugPackageDetails(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  drugConcept ,)java.lang.String  drugConceptType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugPackageDetailResult drugPackageDetails(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String drugConcept,java.lang.String drugConceptType) { 
        LOG.info("Executing operation drugPackageDetails");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(drugConcept);
        System.out.println(drugConceptType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugPackageDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugAllergyInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  allergies ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  proposedMedications ,)java.lang.String  drugStandardType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugAllergyDetailResult drugAllergyInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString allergies,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,java.lang.String drugStandardType) { 
        LOG.info("Executing operation drugAllergyInteraction");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(allergies);
        System.out.println(proposedMedications);
        System.out.println(drugStandardType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugAllergyDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugMonograph(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  drugConcept ,)java.lang.String  drugStandardType ,)java.lang.String  monographFormat )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugMonographResult drugMonograph(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String drugConcept,java.lang.String drugStandardType,java.lang.String monographFormat) { 
        LOG.info("Executing operation drugMonograph");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(drugConcept);
        System.out.println(drugStandardType);
        System.out.println(monographFormat);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugMonographResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#maintainProviderDrugFavoritesArray(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  providerId ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  drugIds ,)java.lang.String  drugStandardType ,)java.lang.String  actionCode )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result maintainProviderDrugFavoritesArray(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String providerId,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString drugIds,java.lang.String drugStandardType,java.lang.String actionCode) { 
        LOG.info("Executing operation maintainProviderDrugFavoritesArray");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(providerId);
        System.out.println(drugIds);
        System.out.println(drugStandardType);
        System.out.println(actionCode);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#validateNDCList(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  ndcList ,)java.lang.String  drugStandardType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.NDCValidationDetailResult validateNDCList(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString ndcList,java.lang.String drugStandardType) { 
        LOG.info("Executing operation validateNDCList");
        System.out.println(credentials);
        System.out.println(ndcList);
        System.out.println(drugStandardType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.NDCValidationDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugDrugInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  currentMedications ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  proposedMedications ,)java.lang.String  drugStandardType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugInteractionResult drugDrugInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString currentMedications,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,java.lang.String drugStandardType) { 
        LOG.info("Executing operation drugDrugInteraction");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(currentMedications);
        System.out.println(proposedMedications);
        System.out.println(drugStandardType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugInteractionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.DrugSoap#drugSearchWithFormulary(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  drugName ,)java.lang.String  includeObsolete ,)java.lang.String  searchBrandGeneric ,)java.lang.String  searchRxOTC ,)java.lang.String  searchDrugSupply )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult drugSearchWithFormulary(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String drugName,java.lang.String includeObsolete,java.lang.String searchBrandGeneric,java.lang.String searchRxOTC,java.lang.String searchDrugSupply) { 
        LOG.info("Executing operation drugSearchWithFormulary");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(drugName);
        System.out.println(includeObsolete);
        System.out.println(searchBrandGeneric);
        System.out.println(searchRxOTC);
        System.out.println(searchDrugSupply);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
