
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-25T16:48:50.945+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Drug",
                      portName = "DrugHttpPost",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "http://preproduction.newcropaccounts.com/V7/WebServices/Drug.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.DrugHttpPost")
                      
public class DrugHttpPostImpl implements DrugHttpPost {

    private static final Logger LOG = Logger.getLogger(DrugHttpPostImpl.class.getName());

}
