package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-29T14:11:58.333+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "FormularySoap")
@XmlSeeAlso({ObjectFactory.class})
public interface FormularySoap {

    /**
     * Identifies the coverage status for a list of drugs based on a particular formulary plan.
     */
    @WebResult(name = "FormularyAlternativesWithDrugInfoResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "FormularyAlternativesWithDrugInfo", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyAlternativesWithDrugInfo")
    @WebMethod(operationName = "FormularyAlternativesWithDrugInfo", action = "https://secure.newcropaccounts.com/V7/webservices/FormularyAlternativesWithDrugInfo")
    @ResponseWrapper(localName = "FormularyAlternativesWithDrugInfoResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyAlternativesWithDrugInfoResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult formularyAlternativesWithDrugInfo(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "healthplanID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanID,
        @WebParam(name = "healthplanTypeID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanTypeID,
        @WebParam(name = "eligibilityIndex", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String eligibilityIndex,
        @WebParam(name = "drugConcept", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConcept,
        @WebParam(name = "drugConceptType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConceptType
    );

    /**
     * Identifies the coverage status for a list of drugs based on a particular formulary plan.
     */
    @WebResult(name = "FormularyAlternativesResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "FormularyAlternatives", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyAlternatives")
    @WebMethod(operationName = "FormularyAlternatives", action = "https://secure.newcropaccounts.com/V7/webservices/FormularyAlternatives")
    @ResponseWrapper(localName = "FormularyAlternativesResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyAlternativesResponse")
    public https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResult formularyAlternatives(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "healthplanID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanID,
        @WebParam(name = "healthplanTypeID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanTypeID,
        @WebParam(name = "eligibilityIndex", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String eligibilityIndex,
        @WebParam(name = "drugConcept", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConcept,
        @WebParam(name = "drugConceptType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConceptType
    );

    @WebResult(name = "HealthplanSearchResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "HealthplanSearch", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.HealthplanSearch")
    @WebMethod(operationName = "HealthplanSearch", action = "https://secure.newcropaccounts.com/V7/webservices/HealthplanSearch")
    @ResponseWrapper(localName = "HealthplanSearchResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.HealthplanSearchResponse")
    public https.secure_newcropaccounts_com.v7.webservices.Result healthplanSearch(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "name", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String name,
        @WebParam(name = "address", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String address,
        @WebParam(name = "city", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String city,
        @WebParam(name = "state", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String state,
        @WebParam(name = "zip", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String zip,
        @WebParam(name = "phone", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String phone,
        @WebParam(name = "fax", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String fax,
        @WebParam(name = "healthplanType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanType,
        @WebParam(name = "healthplanId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        int healthplanId
    );

    /**
     * Identifies the coverage status for a list of drugs based on a particular formulary plan.
     */
    @WebResult(name = "FormularyCoverageResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "FormularyCoverage", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyCoverage")
    @WebMethod(operationName = "FormularyCoverage", action = "https://secure.newcropaccounts.com/V7/webservices/FormularyCoverage")
    @ResponseWrapper(localName = "FormularyCoverageResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageResponse")
    public https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResult formularyCoverage(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "healthplanID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanID,
        @WebParam(name = "healthplanTypeID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanTypeID,
        @WebParam(name = "eligibilityIndex", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String eligibilityIndex,
        @WebParam(name = "drugConcept", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.ArrayOfString drugConcept,
        @WebParam(name = "drugConceptType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConceptType
    );
}
