
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-29T14:11:58.223+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Formulary",
                      portName = "FormularySoap",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "http://preproduction.newcropaccounts.com/V7/WebServices/Formulary.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.FormularySoap")
                      
public class FormularySoapImpl implements FormularySoap {

    private static final Logger LOG = Logger.getLogger(FormularySoapImpl.class.getName());

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.FormularySoap#formularyAlternativesWithDrugInfo(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex ,)java.lang.String  drugConcept ,)java.lang.String  drugConceptType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult formularyAlternativesWithDrugInfo(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex,java.lang.String drugConcept,java.lang.String drugConceptType) { 
        LOG.info("Executing operation formularyAlternativesWithDrugInfo");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        System.out.println(drugConcept);
        System.out.println(drugConceptType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.FormularySoap#formularyAlternatives(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex ,)java.lang.String  drugConcept ,)java.lang.String  drugConceptType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResult formularyAlternatives(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex,java.lang.String drugConcept,java.lang.String drugConceptType) { 
        LOG.info("Executing operation formularyAlternatives");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        System.out.println(drugConcept);
        System.out.println(drugConceptType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.FormularySoap#healthplanSearch(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  name ,)java.lang.String  address ,)java.lang.String  city ,)java.lang.String  state ,)java.lang.String  zip ,)java.lang.String  phone ,)java.lang.String  fax ,)java.lang.String  healthplanType ,)int  healthplanId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result healthplanSearch(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String name,java.lang.String address,java.lang.String city,java.lang.String state,java.lang.String zip,java.lang.String phone,java.lang.String fax,java.lang.String healthplanType,int healthplanId) { 
        LOG.info("Executing operation healthplanSearch");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(name);
        System.out.println(address);
        System.out.println(city);
        System.out.println(state);
        System.out.println(zip);
        System.out.println(phone);
        System.out.println(fax);
        System.out.println(healthplanType);
        System.out.println(healthplanId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.FormularySoap#formularyCoverage(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  drugConcept ,)java.lang.String  drugConceptType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResult formularyCoverage(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString drugConcept,java.lang.String drugConceptType) { 
        LOG.info("Executing operation formularyCoverage");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        System.out.println(drugConcept);
        System.out.println(drugConceptType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
