
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-29T14:11:58.319+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Formulary",
                      portName = "FormularyHttpPost",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "http://preproduction.newcropaccounts.com/V7/WebServices/Formulary.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.FormularyHttpPost")
                      
public class FormularyHttpPostImpl implements FormularyHttpPost {

    private static final Logger LOG = Logger.getLogger(FormularyHttpPostImpl.class.getName());

}
