
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-25T14:36:02.751+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Formulary2",
                      portName = "Formulary2HttpPost",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "http://preproduction.newcropaccounts.com/V7/WebServices/Formulary2.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.Formulary2HttpPost")
                      
public class Formulary2HttpPostImpl implements Formulary2HttpPost {

    private static final Logger LOG = Logger.getLogger(Formulary2HttpPostImpl.class.getName());

}
