package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-25T14:36:02.751+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "Formulary2Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Formulary2Soap {

    /**
     * Identifies the coverage status for a list of drugs based on a particular formulary plan.
     */
    @WebResult(name = "FormularyCompositeResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "FormularyComposite", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyComposite")
    @WebMethod(operationName = "FormularyComposite", action = "https://secure.newcropaccounts.com/V7/webservices/FormularyComposite")
    @ResponseWrapper(localName = "FormularyCompositeResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.FormularyCompositeResponse")
    public https.secure_newcropaccounts_com.v7.webservices.Result formularyComposite(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "healthplanID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanID,
        @WebParam(name = "healthplanTypeID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String healthplanTypeID,
        @WebParam(name = "eligibilityIndex", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String eligibilityIndex,
        @WebParam(name = "drugConcept", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConcept,
        @WebParam(name = "drugConceptType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String drugConceptType,
        @WebParam(name = "includeSchema", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeSchema
    );
}
