package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-11-29T14:11:58.345+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "FormularyHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface FormularyHttpPost {
}
