package https.secure_newcropaccounts_com.v7.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * A web service that performs lab related functions.
 *
 * This class was generated by Apache CXF 2.7.3
 * 2015-09-03T11:52:14.176+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "Lab", 
                  wsdlLocation = "https://preproduction.newcropaccounts.com/v7/WebServices/CI/Lab.asmx?wsdl",
                  targetNamespace = "https://secure.newcropaccounts.com/V7/webservices") 
public class Lab extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://secure.newcropaccounts.com/V7/webservices", "Lab");
    public final static QName LabSoap12 = new QName("https://secure.newcropaccounts.com/V7/webservices", "LabSoap12");
    public final static QName LabSoap = new QName("https://secure.newcropaccounts.com/V7/webservices", "LabSoap");
    public final static QName LabHttpPost = new QName("https://secure.newcropaccounts.com/V7/webservices", "LabHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("https://preproduction.newcropaccounts.com/v7/WebServices/CI/Lab.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Lab.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://preproduction.newcropaccounts.com/v7/WebServices/CI/Lab.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Lab(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Lab(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Lab() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Lab(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Lab(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Lab(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LabSoap
     */
    @WebEndpoint(name = "LabSoap12")
    public LabSoap getLabSoap12() {
        return super.getPort(LabSoap12, LabSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LabSoap
     */
    @WebEndpoint(name = "LabSoap12")
    public LabSoap getLabSoap12(WebServiceFeature... features) {
        return super.getPort(LabSoap12, LabSoap.class, features);
    }
    /**
     *
     * @return
     *     returns LabSoap
     */
    @WebEndpoint(name = "LabSoap")
    public LabSoap getLabSoap() {
        return super.getPort(LabSoap, LabSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LabSoap
     */
    @WebEndpoint(name = "LabSoap")
    public LabSoap getLabSoap(WebServiceFeature... features) {
        return super.getPort(LabSoap, LabSoap.class, features);
    }
    /**
     *
     * @return
     *     returns LabHttpPost
     */
    @WebEndpoint(name = "LabHttpPost")
    public LabHttpPost getLabHttpPost() {
        return super.getPort(LabHttpPost, LabHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LabHttpPost
     */
    @WebEndpoint(name = "LabHttpPost")
    public LabHttpPost getLabHttpPost(WebServiceFeature... features) {
        return super.getPort(LabHttpPost, LabHttpPost.class, features);
    }

}
