
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-09-03T11:52:14.156+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Lab",
                      portName = "LabHttpPost",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "https://preproduction.newcropaccounts.com/v7/WebServices/CI/Lab.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.LabHttpPost")
                      
public class LabHttpPostImpl implements LabHttpPost {

    private static final Logger LOG = Logger.getLogger(LabHttpPostImpl.class.getName());

}
