
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-09-03T11:52:14.056+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Lab",
                      portName = "LabSoap12",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "https://preproduction.newcropaccounts.com/v7/WebServices/CI/Lab.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.LabSoap")
                      
public class LabSoapImpl implements LabSoap {

    private static final Logger LOG = Logger.getLogger(LabSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.LabSoap#getLabResultsPrototype(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId ,)java.lang.String  reportDateCCYYMMDD ,)java.lang.String  includeHL7Result ,)java.lang.String  includeHtmlResult )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.LabResultDetailResult getLabResultsPrototype(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId,java.lang.String reportDateCCYYMMDD,java.lang.String includeHL7Result,java.lang.String includeHtmlResult) { 
        LOG.info("Executing operation getLabResultsPrototype");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        System.out.println(reportDateCCYYMMDD);
        System.out.println(includeHL7Result);
        System.out.println(includeHtmlResult);
        try {
            https.secure_newcropaccounts_com.v7.webservices.LabResultDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.LabSoap#getLabOrders(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId ,)java.lang.String  reportDateCCYYMMDD ,)java.lang.String  includeHL7Result ,)java.lang.String  includeHtmlResult )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.LabOrderDetailResult getLabOrders(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId,java.lang.String reportDateCCYYMMDD,java.lang.String includeHL7Result,java.lang.String includeHtmlResult) { 
        LOG.info("Executing operation getLabOrders");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        System.out.println(reportDateCCYYMMDD);
        System.out.println(includeHL7Result);
        System.out.println(includeHtmlResult);
        try {
            https.secure_newcropaccounts_com.v7.webservices.LabOrderDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.LabSoap#getLabResults(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId ,)java.lang.String  reportDateCCYYMMDD ,)java.lang.String  includeHL7Result ,)java.lang.String  includeHtmlResult )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.LabResultDetailResult getLabResults(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId,java.lang.String reportDateCCYYMMDD,java.lang.String includeHL7Result,java.lang.String includeHtmlResult) { 
        LOG.info("Executing operation getLabResults");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        System.out.println(reportDateCCYYMMDD);
        System.out.println(includeHL7Result);
        System.out.println(includeHtmlResult);
        try {
            https.secure_newcropaccounts_com.v7.webservices.LabResultDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
