package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-09-03T11:52:14.166+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "LabSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LabSoap {

    /**
     * Gets all lab results based on specific criteria.
     */
    @WebResult(name = "GetLabResultsPrototypeResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetLabResultsPrototype", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetLabResultsPrototype")
    @WebMethod(operationName = "GetLabResultsPrototype", action = "https://secure.newcropaccounts.com/V7/webservices/GetLabResultsPrototype")
    @ResponseWrapper(localName = "GetLabResultsPrototypeResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetLabResultsPrototypeResponse")
    public https.secure_newcropaccounts_com.v7.webservices.LabResultDetailResult getLabResultsPrototype(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "locationId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationId,
        @WebParam(name = "licensedPrescriberId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String licensedPrescriberId,
        @WebParam(name = "reportDateCCYYMMDD", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String reportDateCCYYMMDD,
        @WebParam(name = "includeHL7Result", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeHL7Result,
        @WebParam(name = "includeHtmlResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeHtmlResult
    );

    /**
     * Gets all lab orders based on specific criteria.
     */
    @WebResult(name = "GetLabOrdersResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetLabOrders", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetLabOrders")
    @WebMethod(operationName = "GetLabOrders", action = "https://secure.newcropaccounts.com/V7/webservices/GetLabOrders")
    @ResponseWrapper(localName = "GetLabOrdersResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetLabOrdersResponse")
    public https.secure_newcropaccounts_com.v7.webservices.LabOrderDetailResult getLabOrders(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "locationId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationId,
        @WebParam(name = "licensedPrescriberId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String licensedPrescriberId,
        @WebParam(name = "reportDateCCYYMMDD", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String reportDateCCYYMMDD,
        @WebParam(name = "includeHL7Result", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeHL7Result,
        @WebParam(name = "includeHtmlResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeHtmlResult
    );

    /**
     * Gets all lab results based on specific criteria.
     */
    @WebResult(name = "GetLabResultsResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetLabResults", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetLabResults")
    @WebMethod(operationName = "GetLabResults", action = "https://secure.newcropaccounts.com/V7/webservices/GetLabResults")
    @ResponseWrapper(localName = "GetLabResultsResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetLabResultsResponse")
    public https.secure_newcropaccounts_com.v7.webservices.LabResultDetailResult getLabResults(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "locationId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationId,
        @WebParam(name = "licensedPrescriberId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String licensedPrescriberId,
        @WebParam(name = "reportDateCCYYMMDD", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String reportDateCCYYMMDD,
        @WebParam(name = "includeHL7Result", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeHL7Result,
        @WebParam(name = "includeHtmlResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String includeHtmlResult
    );
}
