package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-24T11:24:57.757+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "PatientSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PatientSoap {

    @WebResult(name = "GetPatientUniqueMedicationHistoryResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPatientUniqueMedicationHistory", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientUniqueMedicationHistory")
    @WebMethod(operationName = "GetPatientUniqueMedicationHistory", action = "https://secure.newcropaccounts.com/V7/webservices/GetPatientUniqueMedicationHistory")
    @ResponseWrapper(localName = "GetPatientUniqueMedicationHistoryResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientUniqueMedicationHistoryResponse")
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugNameDetailResult getPatientUniqueMedicationHistory(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "prescriptionHistoryRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester
    );

    @WebResult(name = "GetAccountStatusResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetAccountStatus", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetAccountStatus")
    @WebMethod(operationName = "GetAccountStatus", action = "https://secure.newcropaccounts.com/V7/webservices/GetAccountStatus")
    @ResponseWrapper(localName = "GetAccountStatusResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetAccountStatusResponse")
    public https.secure_newcropaccounts_com.v7.webservices.AccountStatusDetailResult getAccountStatus(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "locationId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String locationId,
        @WebParam(name = "userType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String userType,
        @WebParam(name = "userId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String userId
    );

    /**
     * Refer to the NewCrop Update1 category of web services for newer versions of this web method.
     */
    @WebResult(name = "GetPatientAllergyHistoryResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPatientAllergyHistory", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientAllergyHistory")
    @WebMethod(operationName = "GetPatientAllergyHistory", action = "https://secure.newcropaccounts.com/V7/webservices/GetPatientAllergyHistory")
    @ResponseWrapper(localName = "GetPatientAllergyHistoryResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientAllergyHistoryResponse")
    public https.secure_newcropaccounts_com.v7.webservices.PatientAllergyDetailResult getPatientAllergyHistory(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester
    );

    @WebResult(name = "GetPatientPharmacyHistoryResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPatientPharmacyHistory", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientPharmacyHistory")
    @WebMethod(operationName = "GetPatientPharmacyHistory", action = "https://secure.newcropaccounts.com/V7/webservices/GetPatientPharmacyHistory")
    @ResponseWrapper(localName = "GetPatientPharmacyHistoryResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientPharmacyHistoryResponse")
    public https.secure_newcropaccounts_com.v7.webservices.PatientPharmacyDetailResult getPatientPharmacyHistory(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "maxCount", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        int maxCount,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester
    );

    /**
     * Retrieves PBM eligibility for a given patient.
     */
    @WebResult(name = "GetPBMEligibilityResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPBMEligibility", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPBMEligibility")
    @WebMethod(operationName = "GetPBMEligibility", action = "https://secure.newcropaccounts.com/V7/webservices/GetPBMEligibility")
    @ResponseWrapper(localName = "GetPBMEligibilityResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPBMEligibilityResponse")
    public https.secure_newcropaccounts_com.v7.webservices.EligibilityDetailResult getPBMEligibility(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "xmlIn", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String xmlIn
    );

    /**
     * Refer to the NewCrop Update1 category of web services for newer versions of this web method.
     */
    @WebResult(name = "GetPatientFullMedicationHistory3Result", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPatientFullMedicationHistory3", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientFullMedicationHistory3")
    @WebMethod(operationName = "GetPatientFullMedicationHistory3", action = "https://secure.newcropaccounts.com/V7/webservices/GetPatientFullMedicationHistory3")
    @ResponseWrapper(localName = "GetPatientFullMedicationHistory3Response", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientFullMedicationHistory3Response")
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult3 getPatientFullMedicationHistory3(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "prescriptionHistoryRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,
        @WebParam(name = "patientId", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String patientId,
        @WebParam(name = "patientIdType", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String patientIdType
    );

    /**
     * Retrieves PBM drug history for a given patient.  Refer to the NewCrop Update1 category of web services for newer versions of this web method.
     */
    @WebResult(name = "GetPBMDrugHistoryResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPBMDrugHistory", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPBMDrugHistory")
    @WebMethod(operationName = "GetPBMDrugHistory", action = "https://secure.newcropaccounts.com/V7/webservices/GetPBMDrugHistory")
    @ResponseWrapper(localName = "GetPBMDrugHistoryResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPBMDrugHistoryResponse")
    public https.secure_newcropaccounts_com.v7.webservices.DrugHistoryDetailResult getPBMDrugHistory(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "EligibilityTransactionID", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        java.lang.String eligibilityTransactionID,
        @WebParam(name = "loop", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        int loop
    );

    /**
     * Refer to the NewCrop Update1 category of web services for newer versions of this web method.
     */
    @WebResult(name = "GetPatientFullMedicationHistory2Result", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPatientFullMedicationHistory2", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientFullMedicationHistory2")
    @WebMethod(operationName = "GetPatientFullMedicationHistory2", action = "https://secure.newcropaccounts.com/V7/webservices/GetPatientFullMedicationHistory2")
    @ResponseWrapper(localName = "GetPatientFullMedicationHistory2Response", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientFullMedicationHistory2Response")
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult2 getPatientFullMedicationHistory2(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "prescriptionHistoryRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester
    );

    /**
     * Refer to the NewCrop Update1 category of web services for newer versions of this web method.
     */
    @WebResult(name = "GetPatientFullMedicationHistoryResult", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
    @RequestWrapper(localName = "GetPatientFullMedicationHistory", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientFullMedicationHistory")
    @WebMethod(operationName = "GetPatientFullMedicationHistory", action = "https://secure.newcropaccounts.com/V7/webservices/GetPatientFullMedicationHistory")
    @ResponseWrapper(localName = "GetPatientFullMedicationHistoryResponse", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", className = "https.secure_newcropaccounts_com.v7.webservices.GetPatientFullMedicationHistoryResponse")
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult getPatientFullMedicationHistory(
        @WebParam(name = "credentials", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,
        @WebParam(name = "accountRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,
        @WebParam(name = "patientRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,
        @WebParam(name = "prescriptionHistoryRequest", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,
        @WebParam(name = "patientInformationRequester", targetNamespace = "https://secure.newcropaccounts.com/V7/webservices")
        https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester
    );
}
