
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-24T11:24:57.742+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Patient",
                      portName = "PatientSoap",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "http://preproduction.newcropaccounts.com/V7/WebServices/Patient.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.PatientSoap")
                      
public class PatientSoapImpl1 implements PatientSoap {

    private static final Logger LOG = Logger.getLogger(PatientSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPatientUniqueMedicationHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest  prescriptionHistoryRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugNameDetailResult getPatientUniqueMedicationHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientUniqueMedicationHistory");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(prescriptionHistoryRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientDrugNameDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getAccountStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  userType ,)java.lang.String  userId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.AccountStatusDetailResult getAccountStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String userType,java.lang.String userId) { 
        LOG.info("Executing operation getAccountStatus");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(userType);
        System.out.println(userId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.AccountStatusDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPatientAllergyHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientAllergyDetailResult getPatientAllergyHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientAllergyHistory");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientAllergyDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPatientPharmacyHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)int  maxCount ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientPharmacyDetailResult getPatientPharmacyHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,int maxCount,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientPharmacyHistory");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(maxCount);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientPharmacyDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPBMEligibility(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  xmlIn )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.EligibilityDetailResult getPBMEligibility(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String xmlIn) { 
        LOG.info("Executing operation getPBMEligibility");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(xmlIn);
        try {
            https.secure_newcropaccounts_com.v7.webservices.EligibilityDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPatientFullMedicationHistory3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest  prescriptionHistoryRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  patientId ,)java.lang.String  patientIdType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult3 getPatientFullMedicationHistory3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String patientId,java.lang.String patientIdType) { 
        LOG.info("Executing operation getPatientFullMedicationHistory3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(prescriptionHistoryRequest);
        System.out.println(patientInformationRequester);
        System.out.println(patientId);
        System.out.println(patientIdType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPBMDrugHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  eligibilityTransactionID ,)int  loop )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugHistoryDetailResult getPBMDrugHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String eligibilityTransactionID,int loop) { 
        LOG.info("Executing operation getPBMDrugHistory");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(eligibilityTransactionID);
        System.out.println(loop);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugHistoryDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPatientFullMedicationHistory2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest  prescriptionHistoryRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult2 getPatientFullMedicationHistory2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientFullMedicationHistory2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(prescriptionHistoryRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.PatientSoap#getPatientFullMedicationHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest  prescriptionHistoryRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult getPatientFullMedicationHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientFullMedicationHistory");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(prescriptionHistoryRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
