
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-24T11:24:57.752+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Patient",
                      portName = "PatientHttpPost",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "http://preproduction.newcropaccounts.com/V7/WebServices/Patient.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.PatientHttpPost")
                      
public class PatientHttpPostImpl implements PatientHttpPost {

    private static final Logger LOG = Logger.getLogger(PatientHttpPostImpl.class.getName());

}
