
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-29T12:28:47.159+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Update1",
                      portName = "Update1HttpPost",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "https://preproduction.newcropaccounts.com/v7/WebServices/Update1.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.Update1HttpPost")
                      
public class Update1HttpPostImpl implements Update1HttpPost {

    private static final Logger LOG = Logger.getLogger(Update1HttpPostImpl.class.getName());

}
