
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package https.secure_newcropaccounts_com.v7.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-29T12:28:47.100+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "Update1",
                      portName = "Update1Soap12",
                      targetNamespace = "https://secure.newcropaccounts.com/V7/webservices",
                      wsdlLocation = "https://preproduction.newcropaccounts.com/v7/WebServices/Update1.asmx?wsdl",
                      endpointInterface = "https.secure_newcropaccounts_com.v7.webservices.Update1Soap")
                      
public class Update1SoapImpl implements Update1Soap {

    private static final Logger LOG = Logger.getLogger(Update1SoapImpl.class.getName());

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPrescriptionTransmissionStatusByPatient(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  queryMode ,)java.lang.String  status ,)java.lang.String  subStatus ,)java.lang.String  archiveStatus )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.TransmissionSummaryResult getPrescriptionTransmissionStatusByPatient(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String queryMode,java.lang.String status,java.lang.String subStatus,java.lang.String archiveStatus) { 
        LOG.info("Executing operation getPrescriptionTransmissionStatusByPatient");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(queryMode);
        System.out.println(status);
        System.out.println(subStatus);
        System.out.println(archiveStatus);
        try {
            https.secure_newcropaccounts_com.v7.webservices.TransmissionSummaryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPBMEligibilityV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  xmlIn ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.EligibilityDetailResult getPBMEligibilityV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String xmlIn,java.lang.String includeSchema) { 
        LOG.info("Executing operation getPBMEligibilityV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientInformationRequester);
        System.out.println(xmlIn);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.EligibilityDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getRenewalRequestDetailV4(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  renewalRequestIdentifier ,)java.lang.String  returnEncodedMessage )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalDetailResultV4 getRenewalRequestDetailV4(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String renewalRequestIdentifier,java.lang.String returnEncodedMessage) { 
        LOG.info("Executing operation getRenewalRequestDetailV4");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(renewalRequestIdentifier);
        System.out.println(returnEncodedMessage);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalDetailResultV4 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getAllRenewalRequests(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalSummaryResult getAllRenewalRequests(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId) { 
        LOG.info("Executing operation getAllRenewalRequests");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalSummaryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getAccountStatusV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  userType ,)java.lang.String  userId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.AccountStatusDetailV2Result getAccountStatusV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String userType,java.lang.String userId) { 
        LOG.info("Executing operation getAccountStatusV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(userType);
        System.out.println(userId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.AccountStatusDetailV2Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPrescriptionTransmissionStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  prescriptionIds )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.TransmissionSummaryResult getPrescriptionTransmissionStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String prescriptionIds) { 
        LOG.info("Executing operation getPrescriptionTransmissionStatus");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(prescriptionIds);
        try {
            https.secure_newcropaccounts_com.v7.webservices.TransmissionSummaryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPrescriptionTransmissionStatusV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionTransmissionQueryType  queryType ,)java.lang.String  queryId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.TransmissionSummaryResult getPrescriptionTransmissionStatusV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,https.secure_newcropaccounts_com.v7.webservices.PrescriptionTransmissionQueryType queryType,java.lang.String queryId) { 
        LOG.info("Executing operation getPrescriptionTransmissionStatusV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(queryType);
        System.out.println(queryId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.TransmissionSummaryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getAllRenewalRequestsV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalSummaryResultV2 getAllRenewalRequestsV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId) { 
        LOG.info("Executing operation getAllRenewalRequestsV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalSummaryResultV2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getMeaningfulUsePatientEncounterInfo(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  encounterId ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getMeaningfulUsePatientEncounterInfo(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String encounterId,java.lang.String includeSchema) { 
        LOG.info("Executing operation getMeaningfulUsePatientEncounterInfo");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(encounterId);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getCounselingMessages(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  drugConcept ,)java.lang.String  drugStandardType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.CounselingMessageDetailResult getCounselingMessages(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String drugConcept,java.lang.String drugStandardType) { 
        LOG.info("Executing operation getCounselingMessages");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientInformationRequester);
        System.out.println(drugConcept);
        System.out.println(drugStandardType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.CounselingMessageDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPatientAllergyHistory2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientAllergyExtendedDetailResult getPatientAllergyHistory2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientAllergyHistory2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientAllergyExtendedDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getAllRenewalRequestsV3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId ,)java.lang.String  renewalRequestDate )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalSummaryResultV2 getAllRenewalRequestsV3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId,java.lang.String renewalRequestDate) { 
        LOG.info("Executing operation getAllRenewalRequestsV3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        System.out.println(renewalRequestDate);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalSummaryResultV2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPatientFreeFormAllergyHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientFreeFormAllergyExtendedDetailResult getPatientFreeFormAllergyHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientFreeFormAllergyHistory");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientFreeFormAllergyExtendedDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPatientFullMedicationHistory5(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest  prescriptionHistoryRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  patientIdType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult5 getPatientFullMedicationHistory5(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String patientIdType) { 
        LOG.info("Executing operation getPatientFullMedicationHistory5");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(prescriptionHistoryRequest);
        System.out.println(patientInformationRequester);
        System.out.println(patientIdType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult5 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getSubmittedMessageTransactionStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  messageTransactionId ,)java.lang.String  messageTransactionSource )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.MessageTransactionStatusResult getSubmittedMessageTransactionStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String messageTransactionId,java.lang.String messageTransactionSource) { 
        LOG.info("Executing operation getSubmittedMessageTransactionStatus");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(messageTransactionId);
        System.out.println(messageTransactionSource);
        try {
            https.secure_newcropaccounts_com.v7.webservices.MessageTransactionStatusResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getCompleteMedicationHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  reportDateStartCCYYMMDD ,)java.lang.String  reportDateEndCCYYMMDD ,)java.lang.String  includeSchema ,)java.lang.String  sortOrder )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getCompleteMedicationHistory(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String reportDateStartCCYYMMDD,java.lang.String reportDateEndCCYYMMDD,java.lang.String includeSchema,java.lang.String sortOrder) { 
        LOG.info("Executing operation getCompleteMedicationHistory");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(reportDateStartCCYYMMDD);
        System.out.println(reportDateEndCCYYMMDD);
        System.out.println(includeSchema);
        System.out.println(sortOrder);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getDailyScriptReportV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  reportDateCCYYMMDD ,)int  startHour ,)int  endHour ,)java.lang.String  status ,)java.lang.String  transmissionType ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getDailyScriptReportV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String reportDateCCYYMMDD,int startHour,int endHour,java.lang.String status,java.lang.String transmissionType,java.lang.String includeSchema) { 
        LOG.info("Executing operation getDailyScriptReportV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(reportDateCCYYMMDD);
        System.out.println(startHour);
        System.out.println(endHour);
        System.out.println(status);
        System.out.println(transmissionType);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#healthplanSearchV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  healthplan ,)java.lang.String  state ,)java.lang.String  searchType ,)java.lang.String  resultOrder )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.HealthplanDetailResult healthplanSearchV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String healthplan,java.lang.String state,java.lang.String searchType,java.lang.String resultOrder) { 
        LOG.info("Executing operation healthplanSearchV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(healthplan);
        System.out.println(state);
        System.out.println(searchType);
        System.out.println(resultOrder);
        try {
            https.secure_newcropaccounts_com.v7.webservices.HealthplanDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#registerLicensedPrescriberV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  xmlIn )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RegisterPrescriberDetailV2Result registerLicensedPrescriberV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String xmlIn) { 
        LOG.info("Executing operation registerLicensedPrescriberV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(xmlIn);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RegisterPrescriberDetailV2Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getDailyScriptReport(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  reportDateCCYYMMDD ,)java.lang.String  includeSchema ,)java.lang.String  sortOrder )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getDailyScriptReport(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String reportDateCCYYMMDD,java.lang.String includeSchema,java.lang.String sortOrder) { 
        LOG.info("Executing operation getDailyScriptReport");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(reportDateCCYYMMDD);
        System.out.println(includeSchema);
        System.out.println(sortOrder);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#reportPrescribingCount(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  reportType ,)java.lang.String  reportStartDate ,)java.lang.String  reportEndDate ,)java.lang.String  prescriptionType ,)java.lang.String  prescriptionCount )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result reportPrescribingCount(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String reportType,java.lang.String reportStartDate,java.lang.String reportEndDate,java.lang.String prescriptionType,java.lang.String prescriptionCount) { 
        LOG.info("Executing operation reportPrescribingCount");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientInformationRequester);
        System.out.println(reportType);
        System.out.println(reportStartDate);
        System.out.println(reportEndDate);
        System.out.println(prescriptionType);
        System.out.println(prescriptionCount);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPatientFullMedicationHistory6(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest  prescriptionHistoryRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  patientIdType ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getPatientFullMedicationHistory6(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String patientIdType,java.lang.String includeSchema) { 
        LOG.info("Executing operation getPatientFullMedicationHistory6");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(prescriptionHistoryRequest);
        System.out.println(patientInformationRequester);
        System.out.println(patientIdType);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#generateTestRenewalRequest(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  xmlIn ,)boolean  createCurrentMedFromRxInfo ,)java.lang.String  originalPrescriptionFillDate )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result generateTestRenewalRequest(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String xmlIn,boolean createCurrentMedFromRxInfo,java.lang.String originalPrescriptionFillDate) { 
        LOG.info("Executing operation generateTestRenewalRequest");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(xmlIn);
        System.out.println(createCurrentMedFromRxInfo);
        System.out.println(originalPrescriptionFillDate);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#doseCheck(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  drugId ,)java.lang.String  drugTypeId ,)java.lang.String  birthDateCCYYMMDD ,)java.lang.String  gender ,)java.lang.String  diagnosis ,)java.lang.String  doseType ,)java.lang.String  dose ,)java.lang.String  doseUOM ,)java.lang.String  weightInKg ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result doseCheck(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String drugId,java.lang.String drugTypeId,java.lang.String birthDateCCYYMMDD,java.lang.String gender,java.lang.String diagnosis,java.lang.String doseType,java.lang.String dose,java.lang.String doseUOM,java.lang.String weightInKg,java.lang.String includeSchema) { 
        LOG.info("Executing operation doseCheck");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(drugId);
        System.out.println(drugTypeId);
        System.out.println(birthDateCCYYMMDD);
        System.out.println(gender);
        System.out.println(diagnosis);
        System.out.println(doseType);
        System.out.println(dose);
        System.out.println(doseUOM);
        System.out.println(weightInKg);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getAllRenewalRequestsSummaryV4(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId ,)java.lang.String  renewalRequestDate )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalListSummaryResultV4 getAllRenewalRequestsSummaryV4(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId,java.lang.String renewalRequestDate) { 
        LOG.info("Executing operation getAllRenewalRequestsSummaryV4");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        System.out.println(renewalRequestDate);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalListSummaryResultV4 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#drugAllergyInteractionV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  allergies ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  proposedMedications ,)java.lang.String  drugStandardType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugAllergyDetailResultV2 drugAllergyInteractionV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString allergies,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,java.lang.String drugStandardType) { 
        LOG.info("Executing operation drugAllergyInteractionV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(allergies);
        System.out.println(proposedMedications);
        System.out.println(drugStandardType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugAllergyDetailResultV2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#drugSearchWithFormularyWithFavoritesV3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanId ,)java.lang.String  healthplanTypeId ,)java.lang.String  eligibilityIndex ,)java.lang.String  drugName ,)java.lang.String  drugTypeId ,)java.lang.String  includeObsolete ,)java.lang.String  searchBrandGeneric ,)java.lang.String  searchRxOTC ,)java.lang.String  searchDrugSupply ,)java.lang.String  locationId ,)java.lang.String  providerId ,)java.lang.String  includeCopay ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result drugSearchWithFormularyWithFavoritesV3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanId,java.lang.String healthplanTypeId,java.lang.String eligibilityIndex,java.lang.String drugName,java.lang.String drugTypeId,java.lang.String includeObsolete,java.lang.String searchBrandGeneric,java.lang.String searchRxOTC,java.lang.String searchDrugSupply,java.lang.String locationId,java.lang.String providerId,java.lang.String includeCopay,java.lang.String includeSchema) { 
        LOG.info("Executing operation drugSearchWithFormularyWithFavoritesV3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanId);
        System.out.println(healthplanTypeId);
        System.out.println(eligibilityIndex);
        System.out.println(drugName);
        System.out.println(drugTypeId);
        System.out.println(includeObsolete);
        System.out.println(searchBrandGeneric);
        System.out.println(searchRxOTC);
        System.out.println(searchDrugSupply);
        System.out.println(locationId);
        System.out.println(providerId);
        System.out.println(includeCopay);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPBMDrugHistoryV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  eligibilityTransactionId ,)int  monthsPrior ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugHistoryDetailResult getPBMDrugHistoryV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String eligibilityTransactionId,int monthsPrior,java.lang.String includeSchema) { 
        LOG.info("Executing operation getPBMDrugHistoryV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(eligibilityTransactionId);
        System.out.println(monthsPrior);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugHistoryDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getRenewalRequestDetail(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  renewalRequestIdentifier )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalDetailResult getRenewalRequestDetail(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String renewalRequestIdentifier) { 
        LOG.info("Executing operation getRenewalRequestDetail");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(renewalRequestIdentifier);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPatientFullMedicationHistory4(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest  prescriptionHistoryRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  patientIdType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult4 getPatientFullMedicationHistory4(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PrescriptionHistoryRequest prescriptionHistoryRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String patientIdType) { 
        LOG.info("Executing operation getPatientFullMedicationHistory4");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(prescriptionHistoryRequest);
        System.out.println(patientInformationRequester);
        System.out.println(patientIdType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientDrugDetailResult4 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPBMEligibilityV3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  xmlIn ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.EligibilityDetailResultV3 getPBMEligibilityV3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String xmlIn,java.lang.String includeSchema) { 
        LOG.info("Executing operation getPBMEligibilityV3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientInformationRequester);
        System.out.println(xmlIn);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.EligibilityDetailResultV3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#formularyAlternativesWithDrugInfo2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex ,)java.lang.String  drugConcept ,)java.lang.String  drugConceptType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult formularyAlternativesWithDrugInfo2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex,java.lang.String drugConcept,java.lang.String drugConceptType) { 
        LOG.info("Executing operation formularyAlternativesWithDrugInfo2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        System.out.println(drugConcept);
        System.out.println(drugConceptType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugFormularyDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getMostRecentDownloadUrl(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)int  desiredData )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DownloadDetailResult getMostRecentDownloadUrl(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,int desiredData) { 
        LOG.info("Executing operation getMostRecentDownloadUrl");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(desiredData);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DownloadDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#resolveFailedPrescriptionTransmission(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  prescriptionType ,)java.lang.String  transactionId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result resolveFailedPrescriptionTransmission(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String prescriptionType,java.lang.String transactionId) { 
        LOG.info("Executing operation resolveFailedPrescriptionTransmission");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientInformationRequester);
        System.out.println(prescriptionType);
        System.out.println(transactionId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#formularyCoverageV3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  drugConcept ,)java.lang.String  drugConceptType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResultV3 formularyCoverageV3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString drugConcept,java.lang.String drugConceptType) { 
        LOG.info("Executing operation formularyCoverageV3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        System.out.println(drugConcept);
        System.out.println(drugConceptType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.FormularyCoverageDetailResultV3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getAllRenewalRequestsDetailV4(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId ,)java.lang.String  renewalRequestDate )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalListDetailResultV4 getAllRenewalRequestsDetailV4(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId,java.lang.String renewalRequestDate) { 
        LOG.info("Executing operation getAllRenewalRequestsDetailV4");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        System.out.println(renewalRequestDate);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalListDetailResultV4 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getSideEffects(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  drugConcept ,)java.lang.String  drugStandardType ,)java.lang.String  diseaseDescriptionType ,)java.lang.String  includeSchema ,)java.lang.String  sortOrder )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getSideEffects(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String drugConcept,java.lang.String drugStandardType,java.lang.String diseaseDescriptionType,java.lang.String includeSchema,java.lang.String sortOrder) { 
        LOG.info("Executing operation getSideEffects");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(drugConcept);
        System.out.println(drugStandardType);
        System.out.println(diseaseDescriptionType);
        System.out.println(includeSchema);
        System.out.println(sortOrder);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#sendToRegistry(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  xmlIn )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RegistryDetailResult sendToRegistry(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String xmlIn) { 
        LOG.info("Executing operation sendToRegistry");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(xmlIn);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RegistryDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getDailyScriptReportV3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  reportDateCCYYMMDD ,)int  startHour ,)int  endHour ,)java.lang.String  status ,)java.lang.String  transmissionType ,)java.lang.String  prescriptionType ,)java.lang.String  prescriptionSubType ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getDailyScriptReportV3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String reportDateCCYYMMDD,int startHour,int endHour,java.lang.String status,java.lang.String transmissionType,java.lang.String prescriptionType,java.lang.String prescriptionSubType,java.lang.String includeSchema) { 
        LOG.info("Executing operation getDailyScriptReportV3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(reportDateCCYYMMDD);
        System.out.println(startHour);
        System.out.println(endHour);
        System.out.println(status);
        System.out.println(transmissionType);
        System.out.println(prescriptionType);
        System.out.println(prescriptionSubType);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getRenewalResponseStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  renewalRequestIdentifier ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getRenewalResponseStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String renewalRequestIdentifier,java.lang.String includeSchema) { 
        LOG.info("Executing operation getRenewalResponseStatus");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(renewalRequestIdentifier);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#drugSearchWithFormularyWithFavoritesV2(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex ,)java.lang.String  drugName ,)java.lang.String  includeObsolete ,)java.lang.String  searchBrandGeneric ,)java.lang.String  searchRxOTC ,)java.lang.String  searchDrugSupply ,)java.lang.String  locationId ,)java.lang.String  providerId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugFormularyFavoriteDetailResult drugSearchWithFormularyWithFavoritesV2(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex,java.lang.String drugName,java.lang.String includeObsolete,java.lang.String searchBrandGeneric,java.lang.String searchRxOTC,java.lang.String searchDrugSupply,java.lang.String locationId,java.lang.String providerId) { 
        LOG.info("Executing operation drugSearchWithFormularyWithFavoritesV2");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        System.out.println(drugName);
        System.out.println(includeObsolete);
        System.out.println(searchBrandGeneric);
        System.out.println(searchRxOTC);
        System.out.println(searchDrugSupply);
        System.out.println(locationId);
        System.out.println(providerId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugFormularyFavoriteDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#drugDiseaseInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  diseaseList ,)java.lang.String  diseaseCodeType ,)https.secure_newcropaccounts_com.v7.webservices.ArrayOfString  proposedMedications ,)java.lang.String  drugStandardType )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.DrugDiseaseDetailResult drugDiseaseInteraction(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString diseaseList,java.lang.String diseaseCodeType,https.secure_newcropaccounts_com.v7.webservices.ArrayOfString proposedMedications,java.lang.String drugStandardType) { 
        LOG.info("Executing operation drugDiseaseInteraction");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        System.out.println(diseaseList);
        System.out.println(diseaseCodeType);
        System.out.println(proposedMedications);
        System.out.println(drugStandardType);
        try {
            https.secure_newcropaccounts_com.v7.webservices.DrugDiseaseDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#generateMeaningfulUseUtilizationReport(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  licensedPrescriberId ,)java.lang.String  startDateCCYYMMDD ,)java.lang.String  endDateCCYYMMDD ,)int  quarterNumber ,)java.lang.String  quarterYearCCYY ,)https.secure_newcropaccounts_com.v7.webservices.TimePeriodQueryType  timePeriodQueryType ,)java.lang.String  includeSchema )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.ReportDetailResult generateMeaningfulUseUtilizationReport(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String licensedPrescriberId,java.lang.String startDateCCYYMMDD,java.lang.String endDateCCYYMMDD,int quarterNumber,java.lang.String quarterYearCCYY,https.secure_newcropaccounts_com.v7.webservices.TimePeriodQueryType timePeriodQueryType,java.lang.String includeSchema) { 
        LOG.info("Executing operation generateMeaningfulUseUtilizationReport");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientInformationRequester);
        System.out.println(licensedPrescriberId);
        System.out.println(startDateCCYYMMDD);
        System.out.println(endDateCCYYMMDD);
        System.out.println(quarterNumber);
        System.out.println(quarterYearCCYY);
        System.out.println(timePeriodQueryType);
        System.out.println(includeSchema);
        try {
            https.secure_newcropaccounts_com.v7.webservices.ReportDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getMeaningfulUseUtilizationReport(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester ,)java.lang.String  reportTransactionId )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.ReportDownloadResult getMeaningfulUseUtilizationReport(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester,java.lang.String reportTransactionId) { 
        LOG.info("Executing operation getMeaningfulUseUtilizationReport");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientInformationRequester);
        System.out.println(reportTransactionId);
        try {
            https.secure_newcropaccounts_com.v7.webservices.ReportDownloadResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#pharmacySearchV4(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  postalCode ,)java.lang.String  phoneNumber ,)java.lang.String  streetName ,)java.lang.String  pharmacyName ,)java.lang.String  city ,)java.lang.String  state ,)java.lang.String  ncpdpID ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex ,)java.lang.String  pharmacyType ,)java.lang.String  open24Hours ,)java.lang.String  specialtyID ,)java.lang.String  extraQuery1 ,)java.lang.String  extraQuery2 ,)java.lang.String  extraQuery3 ,)java.lang.String  extraQuery4 )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PharmacyDetailResultV4 pharmacySearchV4(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String postalCode,java.lang.String phoneNumber,java.lang.String streetName,java.lang.String pharmacyName,java.lang.String city,java.lang.String state,java.lang.String ncpdpID,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex,java.lang.String pharmacyType,java.lang.String open24Hours,java.lang.String specialtyID,java.lang.String extraQuery1,java.lang.String extraQuery2,java.lang.String extraQuery3,java.lang.String extraQuery4) { 
        LOG.info("Executing operation pharmacySearchV4");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(postalCode);
        System.out.println(phoneNumber);
        System.out.println(streetName);
        System.out.println(pharmacyName);
        System.out.println(city);
        System.out.println(state);
        System.out.println(ncpdpID);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        System.out.println(pharmacyType);
        System.out.println(open24Hours);
        System.out.println(specialtyID);
        System.out.println(extraQuery1);
        System.out.println(extraQuery2);
        System.out.println(extraQuery3);
        System.out.println(extraQuery4);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PharmacyDetailResultV4 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#sendMissingHealthplanInformation(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  healthplanName ,)java.lang.String  healthplanId ,)java.lang.String  healthplanAddress1 ,)java.lang.String  healthplanAddress2 ,)java.lang.String  healthplanCity ,)java.lang.String  healthplanStateCode ,)java.lang.String  healthplanZip ,)java.lang.String  healthplanZip4 ,)java.lang.String  healthplanPhoneNumber )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result sendMissingHealthplanInformation(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String healthplanName,java.lang.String healthplanId,java.lang.String healthplanAddress1,java.lang.String healthplanAddress2,java.lang.String healthplanCity,java.lang.String healthplanStateCode,java.lang.String healthplanZip,java.lang.String healthplanZip4,java.lang.String healthplanPhoneNumber) { 
        LOG.info("Executing operation sendMissingHealthplanInformation");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(healthplanName);
        System.out.println(healthplanId);
        System.out.println(healthplanAddress1);
        System.out.println(healthplanAddress2);
        System.out.println(healthplanCity);
        System.out.println(healthplanStateCode);
        System.out.println(healthplanZip);
        System.out.println(healthplanZip4);
        System.out.println(healthplanPhoneNumber);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#processRenewalRequest(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  xmlIn )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result processRenewalRequest(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String xmlIn) { 
        LOG.info("Executing operation processRenewalRequest");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(xmlIn);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPatientAllergyHistoryV3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getPatientAllergyHistoryV3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientAllergyHistoryV3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getPatientAllergyHistoryV4(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientRequest  patientRequest ,)https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester  patientInformationRequester )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PatientAllergyExtendedDetailV4Result getPatientAllergyHistoryV4(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,https.secure_newcropaccounts_com.v7.webservices.PatientRequest patientRequest,https.secure_newcropaccounts_com.v7.webservices.PatientInformationRequester patientInformationRequester) { 
        LOG.info("Executing operation getPatientAllergyHistoryV4");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(patientRequest);
        System.out.println(patientInformationRequester);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PatientAllergyExtendedDetailV4Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getAccountStatusDetail(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  locationId ,)java.lang.String  licensedPrescriberId ,)java.lang.String  statusSectionType ,)java.lang.String  includeSchema ,)java.lang.String  sortOrder )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.Result getAccountStatusDetail(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String locationId,java.lang.String licensedPrescriberId,java.lang.String statusSectionType,java.lang.String includeSchema,java.lang.String sortOrder) { 
        LOG.info("Executing operation getAccountStatusDetail");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(locationId);
        System.out.println(licensedPrescriberId);
        System.out.println(statusSectionType);
        System.out.println(includeSchema);
        System.out.println(sortOrder);
        try {
            https.secure_newcropaccounts_com.v7.webservices.Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#pharmacySearchV3(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  postalCode ,)java.lang.String  phoneNumber ,)java.lang.String  streetName ,)java.lang.String  pharmacyName ,)java.lang.String  city ,)java.lang.String  state ,)java.lang.String  ncpdpID ,)java.lang.String  healthplanID ,)java.lang.String  healthplanTypeID ,)java.lang.String  eligibilityIndex )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.PharmacyDetailResultV2 pharmacySearchV3(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String postalCode,java.lang.String phoneNumber,java.lang.String streetName,java.lang.String pharmacyName,java.lang.String city,java.lang.String state,java.lang.String ncpdpID,java.lang.String healthplanID,java.lang.String healthplanTypeID,java.lang.String eligibilityIndex) { 
        LOG.info("Executing operation pharmacySearchV3");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(postalCode);
        System.out.println(phoneNumber);
        System.out.println(streetName);
        System.out.println(pharmacyName);
        System.out.println(city);
        System.out.println(state);
        System.out.println(ncpdpID);
        System.out.println(healthplanID);
        System.out.println(healthplanTypeID);
        System.out.println(eligibilityIndex);
        try {
            https.secure_newcropaccounts_com.v7.webservices.PharmacyDetailResultV2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see https.secure_newcropaccounts_com.v7.webservices.Update1Soap#getRenewalResponseTransmissionStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials  credentials ,)https.secure_newcropaccounts_com.v7.webservices.AccountRequest  accountRequest ,)java.lang.String  renewalRequestIdentifier )*
     */
    public https.secure_newcropaccounts_com.v7.webservices.RenewalResponseDetailResult getRenewalResponseTransmissionStatus(https.secure_newcropaccounts_com.v7.webservices.Credentials credentials,https.secure_newcropaccounts_com.v7.webservices.AccountRequest accountRequest,java.lang.String renewalRequestIdentifier) { 
        LOG.info("Executing operation getRenewalResponseTransmissionStatus");
        System.out.println(credentials);
        System.out.println(accountRequest);
        System.out.println(renewalRequestIdentifier);
        try {
            https.secure_newcropaccounts_com.v7.webservices.RenewalResponseDetailResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
