package https.secure_newcropaccounts_com.v7.webservices;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-10-29T12:28:47.177+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "https://secure.newcropaccounts.com/V7/webservices", name = "Update1HttpPost")
@XmlSeeAlso({com.newcropaccounts.secure.interfacev7.ObjectFactory.class, ObjectFactory.class, com.newcropaccounts.secure.interfacev7.ncstandard.ObjectFactory.class})
public interface Update1HttpPost {
}
