package com.clinakos.rules


import com.clinakos.data.model.rules.HepatitisCRulesData
import com.clinakos.data.model.rules.MedPlan

import java.util.*
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.node.ObjectNode

global ObjectMapper mapper;

rule "HepatitisC Condition 1"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NA",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not Applicable");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
end

rule "HepatitisC Condition 2"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NA",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + simeprevir (150mg) with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) ");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class I, Level B; Class IIb , Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 3"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="NT", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Testing for Q80K polymorphism recommended.  Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG ");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 4"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="NT", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Testing for Q80K polymorphism recommended. Daily Sovaldi (sofosbuvir) 400mg + Simeprevir (150mg) with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) ");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class I, Level B; Class IIb , Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 5"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="N", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Simeprevir 150mg X 12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG for 24 weeks");
      recommendations.put("altRecDuration","Simeprevir- 12 weeks; Ribavirin + PEG - 24 weeks");
      recommendations.put("recommendationLevel","Class I, Level A; Class IIa , Level A (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 6"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="N", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir (150mg) with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class I, Level B; Class IIb , Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 7"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="Y", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 8"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="Y", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir (150mg) with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class I, Level B; Class IIb , Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 9"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1b",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Simeprevir 150mg X 12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG for 24 weeks)");
      recommendations.put("altRecDuration","Simeprevir- 12 weeks; Ribavirin + PEG - 24 weeks");
      recommendations.put("recommendationLevel","Class I, Level A; Class IIa , Level A (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 10"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1b",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir (150mg) with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class I, Level B; Class IIb , Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 11"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG x 12-24 weeks");
      recommendations.put("durationTreatment","Sovaldi (Sofosbuvir)-12 weeks; Ribavirin + PEG- 12 to 24 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 12"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment"," ");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) ");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 13"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Alternative Regimen 1- Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG x 12-24 weeks   OR   Alternative Regimen 2- Daily Simeprevir 150mg X 12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG X 48 weeks");
      recommendations.put("altRecDuration","Alternative Regiment 1- Sovaldi (sofosbuvir) - 12weeks, Ribavirin + PEG- 12 to 24 weeks; Alternative Regimen 2- Simeprevir 12 weeks, Ribavirin + PEG - 48 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C; Class IIa, Level A (second alternataive)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 14"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 11 NA YYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NA",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG x 12-24 weeks");
      recommendations.put("durationTreatment","Sovaldi (Sofosbuvir)-12 weeks; Ribavirin + PEG- 12 to 24 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 11 1a YYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG x 12-24 weeks");
      recommendations.put("durationTreatment","Sovaldi (Sofosbuvir)-12 weeks; Ribavirin + PEG- 12 to 24 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 11 1b YYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1b",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG x 12-24 weeks");
      recommendations.put("durationTreatment","Sovaldi (Sofosbuvir)-12 weeks; Ribavirin + PEG- 12 to 24 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 12 NA NYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NA",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","See Alternative Recommendation");
      recommendations.put("durationTreatment"," ");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) ");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 12 1a NYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","See Alternative Recommendation");
      recommendations.put("durationTreatment"," ");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) ");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 12	 1b NYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1b",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","See Alternative Recommendation");
      recommendations.put("durationTreatment"," ");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) ");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 13 NA YYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NA",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks	");
      recommendations.put("altRecommendation","Alternative Regimen 1- Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG x 12-24 weeks   OR   Alternative Regimen 2- Daily Simeprevir 150mg X 12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG X 48 weeks");
      recommendations.put("altRecDuration","Alternative Regiment 1- Sovaldi (sofosbuvir) - 12weeks, Ribavirin + PEG- 12 to 24 weeks; Alternative Regimen 2- Simeprevir 12 weeks, Ribavirin + PEG - 48 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C; Class IIa, Level A (second alternataive)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 13 1a YYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks	");
      recommendations.put("altRecommendation","Alternative Regimen 1- Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG x 12-24 weeks   OR   Alternative Regimen 2- Daily Simeprevir 150mg X 12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG X 48 weeks");
      recommendations.put("altRecDuration","Alternative Regiment 1- Sovaldi (sofosbuvir) - 12weeks, Ribavirin + PEG- 12 to 24 weeks; Alternative Regimen 2- Simeprevir 12 weeks, Ribavirin + PEG - 48 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C; Class IIa, Level A (second alternataive)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
       rule "HepatitisC Condition 13 1b YYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1b",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks	");
      recommendations.put("altRecommendation","Alternative Regimen 1- Daily Sovaldi (sofosbuvir) 400mg x12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG x 12-24 weeks   OR   Alternative Regimen 2- Daily Simeprevir 150mg X 12 weeks + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) and weekly PEG X 48 weeks");
      recommendations.put("altRecDuration","Alternative Regiment 1- Sovaldi (sofosbuvir) - 12weeks, Ribavirin + PEG- 12 to 24 weeks; Alternative Regimen 2- Simeprevir 12 weeks, Ribavirin + PEG - 48 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C; Class IIa, Level A (second alternataive)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
       rule "HepatitisC Condition 14 NA NYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="NA",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks	");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 14 1a NYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1a",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks	");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 14 1b NYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g1",subGenotype=="1b",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (sofosbuvir) 400mg + Simeprevir 150mg with or without weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])x 12 weeks");
      recommendations.put("durationTreatment","12 weeks	");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg  + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level C");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
     
      
      
      rule "HepatitisC Condition 15"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Any", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 16"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 17"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment to 16 weeks");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12weeks ");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 17 Y"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 17 N"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
       rule "HepatitisC Condition 17 NYNA"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="NA")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment to 16 weeks");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 17 NYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment to 16 weeks");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
       rule "HepatitisC Condition 17 NYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment to 16 weeks");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
       rule "HepatitisC Condition 17 YYNA"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="NA")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment to 16 weeks");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12weeks ");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A; Class IIa, Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 17 YYY"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="Y")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment to 16 weeks");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12weeks ");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A; Class IIa, Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      rule "HepatitisC Condition 17 YYN"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g2",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment to 16 weeks");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12weeks ");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A; Class IIa, Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 18"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g3",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="NA")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X12 weeks.  Patients with Cirrhosis might benefit from extension of treatment");
      recommendations.put("durationTreatment","12 weeks (16 weeks for patients with cirrhosis)");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12weeks");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level A; Class IIa, Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 19"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g3",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("durationTreatment","24 weeks)");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class I, Level B");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 20"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g3",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("durationTreatment","24 weeks)");
      recommendations.put("altRecommendation","Daily Sovaldi (sofosbuvir) 400mg and weight-based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) plus weekly PEG X 12 weeks");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class I, Level B; Class Iia, Level A (Alternative Regimen)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 21"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g3",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("durationTreatment","24 weeks)");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class IIa, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 22"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g3",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) X 24 weeks");
      recommendations.put("durationTreatment","24 weeks)");
      recommendations.put("altRecommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12 weeks");
      recommendations.put("altRecDuration","12 weeks");
      recommendations.put("recommendationLevel","Class IIa, Level A");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 23"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g4",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg/d + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12 weeks");
      recommendations.put("durationTreatment","12 weeks)");
      recommendations.put("altRecommendation","Daily Simeprevir 150 mg x 12 weeks and weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + PEG weekly X24-48 weeks");
      recommendations.put("altRecDuration","Simeprevir- 12 weeks, Ribavirin + PEG- 24-48 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level B");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 24"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g4",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg+ weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) x 24 weeks");
      recommendations.put("durationTreatment","24 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration","Not applicable");
      recommendations.put("recommendationLevel","Class IIb, Level B");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 25"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g4",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + weekly PEG X 12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])  X 24 weeks");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIa, Level C; Class IIa, Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 26"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g4",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="N")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","See Alternative Recommendation");
      recommendations.put("durationTreatment","Not Applicable ");
      recommendations.put("altRecommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg])  X 24 weeks");
      recommendations.put("altRecDuration","24 weeks");
      recommendations.put("recommendationLevel","Class IIa, Level B (Alternative)");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 27"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g56",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + PEG weekly x 12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","Daily weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + PEG weekly x 48 weeks");
      recommendations.put("altRecDuration","48 weeks");
      recommendations.put("recommendationLevel","Class IIb, Level B");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 28"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g56",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="N",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","No Recommendations by AASLD");
      recommendations.put("durationTreatment"," ");
      recommendations.put("altRecommendation"," ");
      recommendations.put("altRecDuration"," ");
      recommendations.put("recommendationLevel"," ");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
      rule "HepatitisC Condition 29"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g56",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="Y", hcvTreatment =="Y",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","Daily Sovaldi (Sofosbuvir) 400 mg + weight based Ribavirin (1000mg [<75 kg] to 1200mg [> 75 kg]) + PEG weekly x 12 weeks");
      recommendations.put("durationTreatment","12 weeks");
      recommendations.put("altRecommendation","None");
      recommendations.put("altRecDuration"," ");
      recommendations.put("recommendationLevel","Class Iia, Level B");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
       rule "HepatitisC Condition 30"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi",genoType=="g56",subGenotype=="NotApplicable",polymorphism=="NotApplicable", ifnEligibility=="N", hcvTreatment =="Y",
		    proteaseInhibitor=="NotApplicable")
	then	
	
	 ObjectNode recommendations = mapper.createObjectNode();
      recommendations.put("recommendation","No Recommendations by AASLD");
      recommendations.put("durationTreatment"," ");
      recommendations.put("altRecommendation"," ");
      recommendations.put("altRecDuration"," ");
      recommendations.put("recommendationLevel"," ");
      recommendations.put("source","AASLD March 2014");
      m.setResponse(recommendations.toString());
      System.out.println("recomendation string "+recommendations.toString());
      
      
      end
      
     rule "Hepatitis UI master data for Monitoring Parameters"
	when
		m:	HepatitisCRulesData( medicine == "sovaldi", MonitorParameter=="Yes")
	then
		 System.out.println("Inside UI datalist");
		  List<String>monitoringParameters=new ArrayList<String>();
			 monitoringParameters.add("Sustained Viral Response (SVR)");
		     monitoringParameters.add("Hgb");
		 	 m.setResponseList(monitoringParameters);
		 
end

 rule "Hepatitis Lab parameters default values SVR"
	when
		m:HepatitisCRulesData(medicine =="sovaldi",request == Request.ACTION_PLAN,MonitorParameter=="SVR")		
	then
	 System.out.println("Inside Default datalist");
		List<MedPlan>defaultMedPlan=new ArrayList<MedPlan>();
		MedPlan medPlanObj_1=new MedPlan();
		medPlanObj_1.setMonitoringParameter("HCV RNA SerPl PCR-aCnc");
		medPlanObj_1.setParameterShortName("HCV RNA SerPl PCR-aCnc");
		defaultMedPlan.add(medPlanObj_1);
		
		MedPlan medPlanObj_2=new MedPlan();
		medPlanObj_2.setMonitoringParameter("HCV RNA SerPl Ql PCR");
		medPlanObj_2.setParameterShortName("HCV RNA SerPl Ql PCR");
		defaultMedPlan.add(medPlanObj_2);
		
		MedPlan medPlanObj_3=new MedPlan();
		medPlanObj_3.setMonitoringParameter("HCV RNA SerPl PCR-Log IU");
		medPlanObj_3.setParameterShortName("HCV RNA SerPl PCR-Log IU");
		defaultMedPlan.add(medPlanObj_3);
		
		MedPlan medPlanObj_4=new MedPlan();
		medPlanObj_4.setMonitoringParameter("HCV RNA SerPl PCR-Log#");
		medPlanObj_4.setParameterShortName("HCV RNA SerPl PCR-Log#");
		defaultMedPlan.add(medPlanObj_4);
		
		m.setMedPlanDefaultSettings(defaultMedPlan);
end

rule "Hepatitis Lab parameters default values HGB"
	when
		m:HepatitisCRulesData(medicine =="sovaldi",request == Request.ACTION_PLAN,MonitorParameter=="Hgb")		
	then
	 System.out.println("Inside Default datalist");
		List<MedPlan>defaultMedPlan=new ArrayList<MedPlan>();
		
		MedPlan medPlanObj_5=new MedPlan();
		medPlanObj_5.setMonitoringParameter("Hgb Bld-mCnc");
		medPlanObj_5.setParameterShortName("Hgb Bld-mCnc");
		defaultMedPlan.add(medPlanObj_5);
		
		m.setMedPlanDefaultSettings(defaultMedPlan);
end
 
      
