package com.clinakos.rules

import com.clinakos.data.model.rules.Message
import com.clinakos.data.model.rules.Request
import com.clinakos.data.model.rules.PsychopharmMessage
import com.clinakos.data.model.rules.MedPlan
import java.util.*
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.node.ObjectNode
import java.lang.String
import java.text.DecimalFormat;

global ObjectMapper mapper;
global DecimalFormat decimalFormat;



rule "lithium-PageList"
    when
        m : Message( medicine == "lithium" , request == Request.PAGE_LIST  )
    then
        m.setResponse("Diagnosis,Dosage,ActionPlan");
end

rule "lithium-addMedicine-1"
    when
        m : Message( medicine == "lithium", request == Request.ADD_MEDICINE, ((Integer)m.get("page")) == 1 )
    then
        ObjectNode page = mapper.createObjectNode();
        page.putArray("Strength").add("5 mg");
        page.putArray("Route").add("As directed").add("By mouth").add("Ear, both").add("Ear, left").add("Ear, right");
        page.putArray("Regimen").add("As directed").add("Daily").add("BID").add("TID").add("QID");
        page.put("Allow Substitute", true);
        page.putArray("Days supply").add("7 days").add("10 days").add("15 days").add("30 days");
        page.putArray("Refill").add(0).add(1).add(2).add(3).add(4).add(5).add(6);
        m.setResponse(page.toString());
end

rule "lithium-dosage-1"
	when
		 m : Message( medicine == "lithium", request == Request.DOSAGE, ((Integer)m.get("page")) == 1)
	then
		ObjectNode page = mapper.createObjectNode();
		page.put("CrCl",0.9);
		page.putArray("Pregnancy").add("No").add("Yes").add("Dont know");
		page.putArray("Drug Screening").add("Yes").add("No");
		m.setResponse(page.toString());
end
		
rule "lithium-dosage-3"
	when
		 m : Message( medicine == "lithium", request == Request.DOSAGE, ((Integer)m.get("page")) == 3)
	then
		ObjectNode page = mapper.createObjectNode();
		page.putArray("Frequency").add("4-5 days");
		page.putArray("BP").add("Every 3 months");
		page.putArray("Creatinine").add("Every 3 months");
		page.putArray("BMI").add("Every 3 months");
		page.putArray("FBS").add("Every 3 months");
		page.putArray("TG").add("Every 3 months");
		page.putArray("HDL").add("Every 3 months");
		page.putArray("Phase").add("Initiation").add("Maintenance");
		m.setResponse(page.toString());
end

rule "lithium-maintenance-1"
	when
		 m : Message( medicine == "lithium", request == Request.MAINTENANCE, ((Integer)m.get("page")) == 1)
	then
		ObjectNode page = mapper.createObjectNode();
		page.putArray("Confirm day").add("4-5 days").add("Maintenance");
		page.put("CrCl", 19.9);
		m.setResponse(page.toString());
end

rule "lithium-maintenance-3"
	when
		 m : Message( medicine == "lithium", request == Request.MAINTENANCE, ((Integer)m.get("page")) == 3)
	then
		ObjectNode page = mapper.createObjectNode();
		page.putArray("Next Lab").add("1 day").add("2 days").add("3 days").add("1 week")
				.add("2 weeks").add("3 weeks").add("4 weeks").add("5 weeks").add("6 weeks");
		page.putArray("BP").add("Every 3 months");
		page.putArray("Creatinine").add("Every 3 months");
		page.putArray("BMI").add("Every 3 months");
		page.putArray("FBS").add("Every 3 months");
		page.putArray("TG").add("Every 3 months");
		page.putArray("HDL").add("Every 3 months");
		page.putArray("Phase").add("Initiation").add("Maintenance");
		m.setResponse(page.toString());
end


rule "lithium-validate-BMI"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("BMI")	,monitoring_parameter_value >25 )
    then
    	
      decimalFormat.setDecimalSeparatorAlwaysShown(false);
      String recomendationMessageObj="BMI "+decimalFormat.format(m.getMonitoring_parameter_value())+": Lithium may cause weight gain";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recomendationMessageObj);
      System.out.println("Inside BMI drools ");
      m.setResponse(page.toString());
end

rule "lithium-validate-FBS"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("Glucose p fast SerPl-mCnc")	,monitoring_parameter_value >100 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
      String recomendationMessageObj ="FBS "+decimalFormat.format(m.getMonitoring_parameter_value()) +" mg/dL: Patient may have pre-diabetes. Refer for treatment to PCP. Consider alternative med";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recomendationMessageObj);
      m.setResponse(page.toString());
end

rule "lithium-validate-TG"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("Trigl Bld-mCnc")	,monitoring_parameter_value >150 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
     String recomendationMessageObj="TG "+decimalFormat.format(m.getMonitoring_parameter_value()) +" mg/dL: Treat for lipids. Lithium may cause weight gain and subsequent increase in lipids";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recomendationMessageObj);
      m.setResponse(page.toString());
end

rule "lithium-female validate-HDL"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("HDL"),monitoring_parameter_value < 50 ,
        gender.equals("female"))
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
      String recomendationMessageObj="HDL "+decimalFormat.format(m.getMonitoring_parameter_value())+" mg/dL: Treat for lipids. Lithium may cause weight gain and subsequent increase in lipids";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recomendationMessageObj);
      m.setResponse(page.toString());
end

rule "lithium-male validate-HDL"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("HDL"),monitoring_parameter_value < 40 ,
        gender.equals("male"))
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
      String recomendationMessageObj="HDL "+decimalFormat.format(m.getMonitoring_parameter_value())+ " mg/dL: Treat for lipids. Lithium may cause weight gain and subsequent increase in lipids";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recomendationMessageObj);
      m.setResponse(page.toString());
end

rule "lithium-validate-SystolicBP"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("Systolic")	,monitoring_parameter_value >135 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
     String recomendationMessageObj="Systolic BP "+decimalFormat.format(m.getMonitoring_parameter_value())+" mmHg: Consider alternative med";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","high");
      page.put("recomendationMessage",recomendationMessageObj);
      m.setResponse(page.toString());
end

rule "lithium-validate-DiastolicBP"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("Diastolic"),monitoring_parameter_value >85 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    String recomendationMessageObj="Diastolic BP "+decimalFormat.format(m.getMonitoring_parameter_value()) +" mmHg: Consider alternative med";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","high");
      page.put("recomendationMessage",recomendationMessageObj);
      m.setResponse(page.toString());
end

rule "lithium-validate-BUN"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("BUN") )
    then
    
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","EMPTY");
      page.put("recomendationMessage","BUN:do not have recommended value in system");
      m.setResponse(page.toString());
end

/*
rule "lithium-validate-Creatinine"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("Cr")	,monitoring_parameter_value >1.1 )
    then
      decimalFormat.setDecimalSeparatorAlwaysShown(false);
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage","Cr "+decimalFormat.format(m.getMonitoring_parameter_value())+" mg/dL ");
      m.setResponse(page.toString());
end
*/
/*
rule "lithium-validate-normalCrCl"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("CrCl")	,monitoring_parameter_value >50 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    String recommendationMessage="CrCl " +decimalFormat.format(m.getMonitoring_parameter_value()) +" ml/min: Normal Lithium starting dose";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","");
      page.put("recomendationMessage",recommendationMessage);
      m.setResponse(page.toString());
end
*/

rule "lithium-validate-mid range CrCl"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("CrCl")	,monitoring_parameter_value >10 && monitoring_parameter_value <50 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    String recommendationMessage="CrCl " +decimalFormat.format(m.getMonitoring_parameter_value())+" ml/min: 50-75% of starting dose is recommended";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recommendationMessage);
      m.setResponse(page.toString());
end

rule "lithium-validate-higherCrCl"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("CrCl")	, monitoring_parameter_value <10 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    String recommendationMessage="CrCl "+decimalFormat.format(m.getMonitoring_parameter_value())+" ml/min: 25-50% of starting dose is recommended";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","high");
      page.put("recomendationMessage",recommendationMessage);
      m.setResponse(page.toString());
end

rule "lithium-validate-EKG"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("EKG:QTc"), monitoring_parameter_value >450 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    	String recommendationMessage="QTc "+decimalFormat.format(m.getMonitoring_parameter_value())+" msec: Consider alternative med";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","high");
      page.put("recomendationMessage",recommendationMessage);
      m.setResponse(page.toString());
end

rule "lithium-validate-mid range-EKG"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("EKG:QTc"), monitoring_parameter_value >= 425 &&  monitoring_parameter_value<=450)
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    String recommendationMessage="QTc "+decimalFormat.format(m.getMonitoring_parameter_value())+" msec: Consider alternative med";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recommendationMessage);
      m.setResponse(page.toString());
end

rule "lithium-validate-WBC"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("WBC"), monitoring_parameter_value >10.9 )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    String recommendationMessage="WBC "+decimalFormat.format(m.getMonitoring_parameter_value()) + " x 10^3/uL: Possible infection, inaccurate Lithium concentration. Consider alternative med";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recommendationMessage);
      m.setResponse(page.toString());
end

rule "lithium-validate-TSH"
    when
        m : PsychopharmMessage( medicine == "lithium" , request == Request.VALIDATE  ,monitoring_paramater.equals("TSH"),monitoring_parameter_value >5.5  )
    then
     decimalFormat.setDecimalSeparatorAlwaysShown(false);
    String recommendationMessage="TSH "+ decimalFormat.format(m.getMonitoring_parameter_value())+" µIU/mL: Treat for high TSH";
      ObjectNode page = mapper.createObjectNode();
      page.put("alertLevel","medium");
      page.put("recomendationMessage",recommendationMessage);
      m.setResponse(page.toString());
end


rule "Lithium UI master data for contraindicated meds"
	when
		m:	PsychopharmMessage( medicine == "lithium", contraindicatedMedicines==true)
	then
		 
		  List<String>contraindictedMedsList=new ArrayList<String>();
			 contraindictedMedsList.add("NSAIDs");
		     contraindictedMedsList.add("diuretics");
		 	 contraindictedMedsList.add("ACE inhibitors");
		 	 contraindictedMedsList.add("metronidazole");
		 	// contraindictedMedsList.add("acetazolamide"); 
		 	 contraindictedMedsList.add("methyldopa");
		 	 contraindictedMedsList.add("carbamazepine");
		 	 contraindictedMedsList.add("phenytoin");
		 	 m.setResponseList(contraindictedMedsList);
		 
end

rule "Lithium UI master data for contraindicated Diaognosis"
	when
		m:	PsychopharmMessage( medicine == "lithium", contraindicatedDiaognosis==true)
	then
		 
		    List<String>contraindictedDiagnosisList=new ArrayList<String>();
			 contraindictedDiagnosisList.add("Renal insufficiency");
		     contraindictedDiagnosisList.add("CAD");
		 	 contraindictedDiagnosisList.add("recent MI");
		 	 contraindictedDiagnosisList.add("psoriasis");
		 	 contraindictedDiagnosisList.add("Diabetes insipidus");
		 	
		 	 m.setResponseList(contraindictedDiagnosisList);
end


rule "Lithium step 2 Urine Drug Screen test validation"
	when
		m:	PsychopharmMessage( medicine == "lithium", drugScreenSelected==true)
	then
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","medium");
      	 page.put("recomendationMessage","Drug Screening positive: Lithium may cause cognitive impairments, effects evaluation. Consider alternative med");
		 m.setResponse(page.toString());
end

rule "Lithium step 2 Pregnancy test validation"
	when
		m:	PsychopharmMessage( medicine == "lithium", pregnancySelected==true)
	then
		
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage","Pregnancy positive: Consider alternative med");
		 m.setResponse(page.toString());
		  System.out.println("Inside Pregnancy test rule from lithium drl "+page.toString());
end

rule "Lithium step 2 contraindicated Diagnosis validation"
	when
		m:	PsychopharmMessage( medicine == "lithium",current_step=="2", $diagnosis : contraindicatedDiagnosis,   
          $diagnosis contains "Renal insufficiency"||$diagnosis contains "CAD"||$diagnosis contains "recent MI"
          ||$diagnosis contains "psoriasis"||$diagnosis contains "Diabetes insipidus")
	then
		
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage","Contraindicated Medical Diagnosis: Consider alternative med");
		 m.setResponse(page.toString());
		 System.out.println("contraindicated Diagnosis validation "+page.toString());
end

rule "Lithium step 2 contraindicated Medicines validation"
	when
		m:	PsychopharmMessage( medicine == "lithium",current_step=="2", $meds : contraindicatedMeds,   
          $meds contains "NSAIDs"||$meds contains "diuretics"||$meds contains "ACE inhibitors"
          ||$meds contains "psoriasis"||$meds contains "metronidazole"||$meds contains "methyldopa"||$meds contains "carbamazepine"
          ||$meds contains "phenytoin")
	then
		
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","medium");
     	 page.put("recomendationMessage","Contraindicated Medications: Consider alternative med");
		 m.setResponse(page.toString());
		 System.out.println("contraindicated Diagnosis validation "+page.toString());
end



rule "Lithium Diabetes inspideous Recommendation message if Diabetes is checked in Step 2 Dosing Guideline"
	when
		m:PsychopharmMessage( medicine == "lithium",recommedationSystemMessage==true, $diagnosis : contraindicatedDiagnosis,$diagnosis contains "Diabetes insipidus")
	then
		 m.setResponse("Not recommended");
		 System.out.println("Inside :Lithium Diabetes insipidus Recommendation message if Diabetes is checked in Step 2 Dosing Guideline ");
end
	


rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit when patient age >=75"
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3",monitoring_paramater.equals("CrCl")	, monitoring_parameter_value >50,patientAge >= 75)
	then
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","medium");
     	 page.put("recomendationMessage"," :300 mg, BID");
		 m.setResponse(page.toString());
end

rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit when CrCl is empty  "
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3",monitoring_paramater.equals("CrCl")	, monitoring_parameter_value==0,patientAge >= 75)
	then
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","medium");
     	 page.put("recomendationMessage","This recommendation assumes normal CrCl. Please enter patient’s CrCl for more accurate recommendation:300 mg, BID");
		 m.setResponse(page.toString());
end

//added rule on 27 oct 2014
rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit when CrCl is b/w 10 && 50   "
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3",monitoring_paramater.equals("CrCl")	, monitoring_parameter_value > 10 &&  monitoring_parameter_value < 50,patientAge >= 75)
	then
		String recomendationMsg="CrCl "+m.getMonitoring_parameter_value() +" ml/min.Patient age >= 75 years. Consider alternative med:Physician to decide";
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","medium");
     	 page.put("recomendationMessage",recomendationMsg);
		 m.setResponse(page.toString());
end

rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit when CrCl is less than 10   "
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3",monitoring_paramater.equals("CrCl")	, monitoring_parameter_value < 10 ,patientAge >= 75)
	then
		String recomendationMsg="CrCl "+m.getMonitoring_parameter_value() +" ml/min.Patient age >= 75 years. Consider alternative med:Physician to decide";
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","medium");
     	 page.put("recomendationMessage",recomendationMsg);
		 m.setResponse(page.toString());
end
//end


rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit"
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3",monitoring_paramater.equals("CrCl")	, monitoring_parameter_value >50)
	then
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","low");
     	 page.put("recomendationMessage"," :300 mg, TID");
		 m.setResponse(page.toString());
end

rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit when CrCl is not entered in step 1"
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3",monitoring_paramater.equals("CrCl")	, monitoring_parameter_value==0)
	then
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","low");
     	 page.put("recomendationMessage","This recommendation assumes normal CrCl. Please enter patient’s CrCl for more accurate recommendation:300 mg, TID");
		 m.setResponse(page.toString());
end

rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit for medium crcl"
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3", monitoring_paramater.equals("CrCl"), monitoring_parameter_value >10 && monitoring_parameter_value <50)
	then
		String recomendationMsg="CrCl "+m.getMonitoring_parameter_value() +" ml/min. 50-75% of starting dose is recommended. Consider alternative med:300 mg, BID";
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","medium");
     	 page.put("recomendationMessage",recomendationMsg);
		 m.setResponse(page.toString());
end

rule "Lithium CrCl step 3 Recomemended Dose from step 2 submit for High crcl"
	when
		m:PsychopharmMessage( medicine == "lithium",next_step=="3",monitoring_paramater.equals("CrCl"), monitoring_parameter_value <10)
	then
	String recomendationMsg="CrCl "+m.getMonitoring_parameter_value() +" ml/min. Patient has significant renal dysfunction. 25-50% of starting dose is recommended. Consider alternative med:25-50% of starting dose";
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage",recomendationMsg);
		 m.setResponse(page.toString());
end



rule "PHQ-9 scale validation Minimal Depression range >= 0 && <= 4"
	when
		m:PsychopharmMessage( medicine == "lithium", phq9Scale >=0 && phq9Scale <=4 )
	then
		 decimalFormat.setDecimalSeparatorAlwaysShown(false);
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","low");
     	 page.put("recomendationMessage","PHQ-9 Scale "+decimalFormat.format(m.getPhq9Scale())+": Minimal Depression");
		 m.setResponse(page.toString());	
end

rule "PHQ-9 scale validation Mild depression range > 4 && < 9"
	when
		m:PsychopharmMessage( medicine == "lithium", phq9Scale >=5  && phq9Scale <=9 )
	then
		 decimalFormat.setDecimalSeparatorAlwaysShown(false);
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage","PHQ-9 Scale "+decimalFormat.format(m.getPhq9Scale())+": Mild depression");
		 m.setResponse(page.toString());	
end

rule "PHQ-9 scale validation Moderate depression range > 10 && < 14"
	when
		m:PsychopharmMessage( medicine == "lithium", phq9Scale >= 10 && phq9Scale <= 14)
	then
		 decimalFormat.setDecimalSeparatorAlwaysShown(false);
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage","PHQ-9 Scale "+decimalFormat.format(m.getPhq9Scale())+": Moderate depression");
		 m.setResponse(page.toString());	
end

rule "PHQ-9 scale validation Moderately severe depression range > 15 && < 19"
	when
		m:PsychopharmMessage( medicine == "lithium", phq9Scale >= 15 && phq9Scale <= 19)
	then
		 decimalFormat.setDecimalSeparatorAlwaysShown(false);
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage","PHQ-9 Scale "+decimalFormat.format(m.getPhq9Scale())+": Moderately severe depression");
		 m.setResponse(page.toString());	
end

rule "PHQ-9 scale validation Severe depression range > 20 && < 27"
	when
		m:PsychopharmMessage( medicine == "lithium", phq9Scale >= 20 && phq9Scale <= 27)
	then
		 decimalFormat.setDecimalSeparatorAlwaysShown(false);
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage","PHQ-9 Scale "+decimalFormat.format(m.getPhq9Scale())+": Severe depression");
		 m.setResponse(page.toString());	
end

rule "Altman Mania Rating scale for range above 5"
	when
		m:PsychopharmMessage( medicine == "lithium", altmanScale > 5)
	then
		 decimalFormat.setDecimalSeparatorAlwaysShown(false);
		 ObjectNode page = mapper.createObjectNode();
		 page.put("alertLevel","high");
     	 page.put("recomendationMessage","Altman scale "+decimalFormat.format(m.getAltmanScale())+": need for treatment and/or further diagnostic workup to confirm diagnosis of mania or hypomania");
		 m.setResponse(page.toString());	
end


rule "Lithium PHQ-9 questionarre "
	when
		m:PsychopharmMessage( medicine == "lithium", request == Request.QUESTIONS,phq_9==true)
	then
		 Map<String,PsychopharmMessage> labData = new LinkedHashMap<String,PsychopharmMessage>();
		
		 Map<String,String>PHQ_9_options=new LinkedHashMap<String,String>();
		  PHQ_9_options.put("0","Not at all");
		  PHQ_9_options.put("1","Several days");
		  PHQ_9_options.put("2","More than half the days");
		  PHQ_9_options.put("3","Nearly every day");
		 
		 labData.put("Little Interest or pleasure in doing things",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Feeling down,depressed or hopeless",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Trouble falling or staying asleep,or sleeping too much",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Feeling tired or having little energy",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Poor appetite or overeating",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Feeling bad about yourself or that you are a failure or have let yourself or your family down",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Trouble concentrating on things,such as reading the newspaper or watching television",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual",new PsychopharmMessage("",PHQ_9_options));
		 labData.put("Thoughts that you would be better off dead or hurting yourself in some way",new PsychopharmMessage("",PHQ_9_options));
		  m.setPsychopharmPayload(labData);
		 System.out.println("payload data "+labData.toString());
end
//Lithium Altman scale Rating questions
rule "Lithium Altman scale questions "
	when
		m:PsychopharmMessage( medicine == "lithium", request == Request.QUESTIONS)
	then
		 Map<String,PsychopharmMessage> labData = new LinkedHashMap<String,PsychopharmMessage>();
		
		 Map<String,String>altman_options_1=new LinkedHashMap<String,String>();
		  altman_options_1.put("0","I do not feel happier or more cheerful than usual.");
		  altman_options_1.put("1","I occasionally feel happier or more cheerful than usual.");
		  altman_options_1.put("2","I often feel happier or more cheerful than usual.");
		  altman_options_1.put("3","I feel happier or more cheerful than usual most of the time.");
		  altman_options_1.put("4","I feel happier or more cheerful than usual all of the time.");
		 
		  Map<String,String>altman_options_2=new LinkedHashMap<String,String>();
		  altman_options_2.put("0","I do not feel more self-confident than usual.");
		  altman_options_2.put("1","I occasionally feel more self-confident than usual.");
		  altman_options_2.put("2","I often feel more self-confident than usual.");
		  altman_options_2.put("3","I feel more self-confident than usual.");
		  altman_options_2.put("4","I feel extremely self-confident than usual.");
		  
		   Map<String,String>altman_options_3=new LinkedHashMap<String,String>();
		  altman_options_3.put("0","I do not need less sleep than usual.");
		  altman_options_3.put("1","I occasionally need less sleep than usual.");
		  altman_options_3.put("2","I often need less sleep than usual.");
		  altman_options_3.put("3","I frequently need less sleep than usual.");
		  altman_options_3.put("4","I can go all the day and night without any sleep and still not feel tired.");
		  
		   Map<String,String>altman_options_4=new LinkedHashMap<String,String>();
		  altman_options_4.put("0","I do not talk more than usual.");
		  altman_options_4.put("1","I occasionally talk more than usual.");
		  altman_options_4.put("2","I often talk more than usual.");
		  altman_options_4.put("3","I frequently talk more than usual.");
		  altman_options_4.put("4","I talk constantly and cannot be interrupted.");
		  
		    Map<String,String>altman_options_5=new LinkedHashMap<String,String>();
		  altman_options_5.put("0","I have not been more active(either socially,sexually,at work,home or school) than usual.");
		  altman_options_5.put("1","I have occasionally been more active than usual.");
		  altman_options_5.put("2","I have often been more active than usual.");
		  altman_options_5.put("3","I have frequently been more active than usual.");
		  altman_options_5.put("4","I am constantly active or on the go all the time.");
		 
		 labData.put("Question 1",new PsychopharmMessage("",altman_options_1));
		 labData.put("Question 2",new PsychopharmMessage("",altman_options_2));
		 labData.put("Question 3",new PsychopharmMessage("",altman_options_3));
		 labData.put("Question 4",new PsychopharmMessage("",altman_options_4));
		 labData.put("Question 5",new PsychopharmMessage("",altman_options_5));
		
		  m.setPsychopharmPayload(labData);
		 System.out.println("payload data "+labData.toString());
end


//Lithium Adjusting dosing GuideLine Patient Questions
 
rule "Lithium adjusting dose if Lithium level is between 1.2 and 1.5 and ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 1.2 && lithiumLevel <= 1.5)
	then	
		  Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1.Taking NSAIDs (except ASA), thiazide diuretics, ACE inhibitors, antibiotics (tetracycline, metronidazole)?");
		 questions.add("2.Decreased water intake/dehydrated? ");
		 questions.add("3.AEs: Nausea, vomitting, diarrhea, tremors, polyuria, weight gain, loose stools, cognitive impairment?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		   boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	 
end

rule "Lithium adjusting dose if Lithium level is between 1.5 and 2.5 and ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 1.5 && lithiumLevel < 2.5)
	then
		  Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1.Taking NSAIDs (except ASA), thiazide diuretics, ACE inhibitors, antibiotics (tetracycline, metronidazole)?");
		 questions.add("2.Decreased water intake/dehydrated? ");
		 questions.add("3.AEs: Nausea, vomitting, diarrhea, tremors, polyuria, weight gain, loose stools, cognitive impairment?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		   boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	 
end

rule "Lithium adjusting dose if Lithium level is greater than 2.5 and ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel >= 2.5)
	then
		  Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1.Taking NSAIDs (except ASA), thiazide diuretics, ACE inhibitors, antibiotics (tetracycline, metronidazole)?");
		 questions.add("2.Decreased water intake/dehydrated? ");
		 questions.add("3.AEs: Nausea, vomitting, diarrhea, tremors, polyuria, weight gain, loose stools, cognitive impairment?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		   boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	 	
end

/*rule "Lithium adjusting dose if Lithium level is less than 0.8 and ask questions && CrCl is assumed to be > 50"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel < 0.8 , CrCl_Value > 50)
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	 	
end*/

/*rule "Lithium adjusting dose if Lithium level is less than 0.8 & CrCl_Value > 50 then ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel < 0.8 , CrCl_Value > 50)
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	
end*/

rule "Lithium adjusting dose if Lithium level is less than 0.5 & CrCl_Value < 10 then ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5 , CrCl_Value < 10)
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	
end

rule "Lithium adjusting dose if Lithium level is less than 0.5 & CrCl_Value > 50 then ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5 , CrCl_Value > 50)
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	
end

rule "Lithium adjusting dose if Lithium level is less than 0.5 & CrCl is in between 10 & 50 then ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5 , CrCl_Value > 10 && CrCl_Value < 50 )
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);		
end

rule "Lithium adjusting dose if Lithium level is less than 0.5 & CrCl is not available "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5 , CrCl_Value == 0 )
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);		
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 & CrCl > 50 then ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8 , CrCl_Value > 50 )
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		 boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 & CrCl <10 then ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel <  0.8 , CrCl_Value < 10)
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 & CrCl > 10 && CrCl < 50 then ask questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8 , CrCl_Value > 10 &&  CrCl_Value <50)
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 & CrCl is not available "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8 , CrCl_Value == 0)
	then
		 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
		 List<String>questions=new ArrayList<String>();
		 questions.add("1. Taking K-sparing diuretics: aldolactone, theophylline? ");
		 questions.add("2. Sodium intake increased?");
		 
		 Map<String,String>options =new LinkedHashMap<String,String>();
		 options.put("yes","Yes");
		 options.put("no","No");
		  boolean optionsRendered=true;
		 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
		 m.setPsychopharmPayload(questionData);	
end

rule "Lithium adjusting dose if Lithium level is > 0.8 && < 1.2 then no questions "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel >= 0.8 && lithiumLevel <= 1.2,request == Request.ACTION)
	then
	//	 Map<String,PsychopharmMessage> questionData = new LinkedHashMap<String,PsychopharmMessage>();
	//	 List<String>questions=new ArrayList<String>();
		 
	//	 questions.add("1. Check lithium in 4-5 days.");
	//	 questions.add("2. If Li levels remain normal for 2 consecutive checks, then check in 4 weeks.");
	//	  questions.add("3. If levels continue to remain normal x 2 checks, then check every 3-6 months");
	//	 Map<String,String>options =new LinkedHashMap<String,String>();
		//  options.put("yes","Yes");
		// options.put("no","No");
	//	 boolean optionsRendered=false;
	//	 questionData.put("question",new PsychopharmMessage("",questions,options,optionsRendered));
	//	 m.setPsychopharmPayload(questionData);	
	
		 ObjectNode page = mapper.createObjectNode();
     
     	 page.put("recomendationMessage","1. Check Lithium in 4-5 days.\n 2. If Lithium levels remain normal for 2 consecutive checks, then check in 4 weeks.\n 3. If levels continue to remain normal x 2 checks, then check every 3-6 months");
     	 m.setResponse(page.toString());
end


//Recommendations to the Lithium adjusting dose if patient answer yes to the questions 

rule "Lithium adjusting dose if Lithium level is between 1.2 and 1.5 and Patient answer is no"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 1.2 && lithiumLevel <=1.5,patientAnswer == "no" )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","high");
     	 page.put("message","Hold rest of today's dose.");
     	 page.put("recomendationMessage","Reduce dose by 300 mg. Check lithium in 4-5 days");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is between 1.2 and 1.5 and Patient answer is yes"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 1.2 && lithiumLevel <= 1.5,patientAnswer == "yes" )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","high");
     	 page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is between 1.5 and 2.5 and Patient answer is no"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 1.5 && lithiumLevel < 2.5,patientAnswer== "no" )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","high");
     	  page.put("message"," Hold rest of today's dose and tomorrow's dose.");
     	 page.put("recomendationMessage","Reduce dose by 600 mg.  Check lithium in 4-5 days");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is between 1.5 and 2.5 and Patient answer is yes"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 1.5 && lithiumLevel < 2.5,patientAnswer== "yes" )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","high");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 2.5 and Patient answer is yes"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel >= 2.5,patientAnswer== "yes" )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","high");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 2.5 and Patient answer is no"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel >= 2.5,patientAnswer== "no" )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","high");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is no"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "no",CrCl_Value>50 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Incrementally increase dose by 600 mg/day. Check lithium in 4-5 days after every increase");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is yes"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "yes",CrCl_Value>50 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is no && crcl b/w 10 & 50"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "no",CrCl_Value>10 && CrCl_Value<50 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Incrementally increase dose by 50% above 300 mg. Check lithium in 4-5 days after every increase");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is yes && crcl b/w 10 & 50"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "yes",CrCl_Value>10 && CrCl_Value<50 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is no && crcl <10"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "no",CrCl_Value < 10 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is yes && crcl <10 "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "yes",CrCl_Value < 10 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is no"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "no",CrCl_Value > 50 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Incrementally increase total daily dose by 300 mg. Check lithium in 4-5 days after every increase");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is yes"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "yes",CrCl_Value > 50 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is no && crcl is b/w 10-50 "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "no",CrCl_Value > 10 && CrCl_Value < 50)
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Incrementally increase dose by 50% above 150 mg/day. Check lithium in 4-5 days after every increase");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is yes && crcl is b/w 10-50"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "yes",CrCl_Value > 10 && CrCl_Value < 50 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is no && crcl <10 "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "no",CrCl_Value <10)
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is yes && crcl < 10"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "yes",CrCl_Value <10 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

//rule added 27 oct 2014
rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is yes && crcl not available "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "yes",CrCl_Value == 0 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","This recommendation assumes normal CrCl. Please enter patient's CrCl for more accurate recommendation");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is < 0.5 and Patient answer is no && crcl not available "
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel <= 0.5,patientAnswer== "no",CrCl_Value == 0 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","This recommendation assumes normal CrCl. Please enter patient's CrCl for more accurate recommendation");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is yes && crcl not available"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "yes",CrCl_Value == 0 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","This recommendation assumes normal CrCl. Please enter patient's CrCl for more accurate recommendation");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

rule "Lithium adjusting dose if Lithium level is > 0.5 && < 0.7 and Patient answer is no && crcl not available"
	when
		m:PsychopharmMessage( medicine == "lithium", lithiumLevel > 0.5 && lithiumLevel < 0.8,patientAnswer== "no",CrCl_Value == 0 )
	then
		 ObjectNode page = mapper.createObjectNode();
     	 page.put("alertLevel","medium");
     	  page.put("message","This recommendation assumes normal CrCl. Please enter patient's CrCl for more accurate recommendation");
     	 page.put("recomendationMessage","Physician to decide");
     	 m.setResponse(page.toString());
end

//end 27 oct 2014


rule "Lithium step 1 baseline parameters"
	when
		m:PsychopharmMessage(medicine =="lithium", request == Request.MASTER_DATA)
	then
		
		
	
		  String labDate="";
		  Map<String,PsychopharmMessage> labData = new LinkedHashMap<String,PsychopharmMessage>();
		  labData.put("BMI",new PsychopharmMessage("","","BMI","Body Mass Index",labDate));
		  labData.put("Trigl Bld-mCnc",new PsychopharmMessage("","mg/dL","TG","Triglycerides",labDate));
		  labData.put("Cr",new PsychopharmMessage("","mg/dL","Cr","Creatinine",labDate));
		  labData.put("CrCl",new PsychopharmMessage("","ml/min","CrCl","Creatinine Clearance",labDate));
		  labData.put("HDL",new PsychopharmMessage("","mg/dL","HDL","High Density Lipoproteins",labDate));
		  labData.put("Glucose p fast SerPl-mCnc",new PsychopharmMessage("","mg/dL","FBS","Fasting Blood Sugar",labDate));
		  labData.put("EKG:QTc",new PsychopharmMessage("","QTc (msec)","EKG"," Electrocardiogram",labDate));
		  labData.put("WBC",new PsychopharmMessage("","x 10^3/uL","WBC","White Blood Cells",labDate));
		  labData.put("TSH",new PsychopharmMessage("","µIU/mL","TSH","Thyroid Stimulating Hormone",labDate));
		  labData.put("Systolic",new PsychopharmMessage("","mmHg","SBP","Systolic Blood Pressure",labDate));
		  labData.put("Diastolic",new PsychopharmMessage("","mmHg","DBP","Diastolic Blood Pressure",labDate));
	//	  labData.put("BUN",new PsychopharmMessage("","mg/dL"));
		  m.setPsychopharmPayload(labData);
		 System.out.println("payload data "+labData.toString());
	
end

rule "Lithium phase life cycle master data"
	when
		m:PsychopharmMessage(medicine =="lithium", request == Request.PHASE)
	then
		    List<String>phaseList=new ArrayList<String>();
			phaseList.add("Initiation");
			phaseList.add("Maintenance");
		 	m.setResponseList(phaseList);
end

rule "Lithium Lab parameters default values for male"
	when
		m:PsychopharmMessage(medicine =="lithium",request == Request.ACTION_PLAN,gender.equals("male"))		
	then
		List<MedPlan>defaultMedPlan=new ArrayList<MedPlan>();
		MedPlan medPlanObj_1=new MedPlan();
		medPlanObj_1.setMonitoringParameter("Lithium SerPl-mCnc");
		medPlanObj_1.setParameterShortName("Lithium SerPl-mCnc");
		medPlanObj_1.setLabUnit("mEq/L");
		medPlanObj_1.setAlertSevereLowRangeSymbol(">");
		medPlanObj_1.setAlertSevereLowRangeValue(1.2);
		medPlanObj_1.setAlertMediumLowRangeSymbol("<");
		medPlanObj_1.setAlertMediumLowRangeValue(0.8);
		medPlanObj_1.setGoalRangeSymbol(">=");
		medPlanObj_1.setGoalRangeValue(0.8);
		medPlanObj_1.setGoalRangeEndSymbol("<=");
		medPlanObj_1.setGoalRangeEndValue(1.2);
		medPlanObj_1.setFrequencyNo("4");
		defaultMedPlan.add(medPlanObj_1);
		
		MedPlan medPlanObj_12=new MedPlan();
		medPlanObj_12.setMonitoringParameter("Lithium SerPl-sCnc");
		medPlanObj_12.setParameterShortName("Lithium SerPl-sCnc");
		medPlanObj_12.setLabUnit("mEq/L");
		medPlanObj_12.setAlertSevereLowRangeSymbol(">");
		medPlanObj_12.setAlertSevereLowRangeValue(1.2);
		medPlanObj_12.setAlertMediumLowRangeSymbol("<");
		medPlanObj_12.setAlertMediumLowRangeValue(0.8);
		medPlanObj_12.setGoalRangeSymbol(">=");
		medPlanObj_12.setGoalRangeValue(0.8);
		medPlanObj_12.setGoalRangeEndSymbol("<=");
		medPlanObj_12.setGoalRangeEndValue(1.2);
		medPlanObj_12.setFrequencyNo("4");
		defaultMedPlan.add(medPlanObj_12);
		
		MedPlan medPlanObj_2=new MedPlan();
		medPlanObj_2.setMonitoringParameter("Systolic");
		medPlanObj_2.setParameterShortName("Systolic BP");
		medPlanObj_2.setLabUnit("mmHg");
		medPlanObj_2.setAlertSevereLowRangeSymbol(">");
		medPlanObj_2.setAlertSevereLowRangeValue(135);
		defaultMedPlan.add(medPlanObj_2);
		
		MedPlan medPlanObj_3=new MedPlan();
		medPlanObj_3.setMonitoringParameter("Diastolic");
		medPlanObj_3.setParameterShortName("Diastolic BP");
		medPlanObj_3.setLabUnit("mmHg");
		medPlanObj_3.setAlertSevereLowRangeSymbol(">");
		medPlanObj_3.setAlertSevereLowRangeValue(85);
		defaultMedPlan.add(medPlanObj_3);
		
		MedPlan medPlanObj_4=new MedPlan();
		medPlanObj_4.setMonitoringParameter("HDLc SerPl-mCnc");
		medPlanObj_4.setParameterShortName("HDL");
		medPlanObj_4.setLabUnit("mg/dL");
		medPlanObj_4.setAlertMediumLowRangeSymbol("<");
		medPlanObj_4.setAlertMediumLowRangeValue(40);
		defaultMedPlan.add(medPlanObj_4);
		
		MedPlan medPlanObj_5=new MedPlan();
		medPlanObj_5.setMonitoringParameter("TSH");
		medPlanObj_5.setParameterShortName("TSH");
		medPlanObj_5.setLabUnit("mIU/L");
		medPlanObj_5.setAlertMediumLowRangeSymbol(">");
		medPlanObj_5.setAlertMediumLowRangeValue(5.5);
		defaultMedPlan.add(medPlanObj_5);
		
		MedPlan medPlanObj_6=new MedPlan();
		medPlanObj_6.setMonitoringParameter("Cr");
		medPlanObj_6.setParameterShortName("Cr");
		medPlanObj_6.setLabUnit("mg/dL");
		medPlanObj_6.setAlertMediumLowRangeSymbol(">");
		medPlanObj_6.setAlertMediumLowRangeValue(1.1);
		defaultMedPlan.add(medPlanObj_6);
		
		MedPlan medPlanObj_7=new MedPlan();
		medPlanObj_7.setMonitoringParameter("Weight");
		medPlanObj_7.setParameterShortName("Body weight");
		medPlanObj_7.setLabUnit("lb");
		defaultMedPlan.add(medPlanObj_7);
		
		MedPlan medPlanObj_8=new MedPlan();
		medPlanObj_8.setMonitoringParameter("Glucose p fast SerPl-mCnc");
		medPlanObj_8.setParameterShortName("FBS");
		medPlanObj_8.setLabUnit("mg/dL");
		medPlanObj_8.setAlertMediumLowRangeSymbol(">");
		medPlanObj_8.setAlertMediumLowRangeValue(100);
		defaultMedPlan.add(medPlanObj_8);
		
		MedPlan medPlanObj_9=new MedPlan();
		medPlanObj_9.setMonitoringParameter("WBC");
		medPlanObj_9.setParameterShortName("WBC");
		medPlanObj_9.setLabUnit(" x 10^3/uL");
		medPlanObj_9.setAlertMediumLowRangeSymbol(">");
		medPlanObj_9.setAlertMediumLowRangeValue(10.9);
		defaultMedPlan.add(medPlanObj_9);
		
			MedPlan medPlanObj_10=new MedPlan();
		medPlanObj_10.setMonitoringParameter("EKG:QTc");
		medPlanObj_10.setParameterShortName("EKG:QTc");
		medPlanObj_10.setLabUnit("msec");
		medPlanObj_10.setAlertSevereLowRangeSymbol(">");
		medPlanObj_10.setAlertSevereLowRangeValue(450);
		medPlanObj_10.setAlertMediumLowRangeSymbol(">=");
		medPlanObj_10.setAlertMediumLowRangeValue(425);
		medPlanObj_10.setAlertMediumHighRangeSymbol("<=");
		medPlanObj_10.setAlertMediumHighRangeValue(450);
		defaultMedPlan.add(medPlanObj_10);
		
		MedPlan medPlanObj_11=new MedPlan();
		medPlanObj_11.setMonitoringParameter("Trigl Bld-mCnc");
		medPlanObj_11.setParameterShortName("Trigl Bld-mCnc");
		medPlanObj_11.setLabUnit("mg/dL");
		medPlanObj_11.setAlertMediumLowRangeSymbol(">");
		medPlanObj_11.setAlertMediumLowRangeValue(150);
		defaultMedPlan.add(medPlanObj_11);
		
		m.setMedPlanDefaultSettings(defaultMedPlan);
end

rule "Lithium Lab parameters default values for female"
	when
		m:PsychopharmMessage(medicine =="lithium",request == Request.ACTION_PLAN,gender.equals("female"))		
	then
		List<MedPlan>defaultMedPlan=new ArrayList<MedPlan>();
		MedPlan medPlanObj_1=new MedPlan();
		medPlanObj_1.setMonitoringParameter("Lithium SerPl-mCnc");
		medPlanObj_1.setParameterShortName("Lithium SerPl-mCnc");
		medPlanObj_1.setLabUnit("mEq/L");
		medPlanObj_1.setAlertSevereLowRangeSymbol(">");
		medPlanObj_1.setAlertSevereLowRangeValue(1.2);
		medPlanObj_1.setAlertMediumLowRangeSymbol("<");
		medPlanObj_1.setAlertMediumLowRangeValue(0.8);
		medPlanObj_1.setGoalRangeSymbol(">=");
		medPlanObj_1.setGoalRangeValue(0.8);
		medPlanObj_1.setGoalRangeEndSymbol("<=");
		medPlanObj_1.setGoalRangeEndValue(1.2);
		medPlanObj_1.setFrequencyNo("4");
		defaultMedPlan.add(medPlanObj_1);
		
		MedPlan medPlanObj_12=new MedPlan();
		medPlanObj_12.setMonitoringParameter("Lithium SerPl-sCnc");
		medPlanObj_12.setParameterShortName("Lithium SerPl-sCnc");
		medPlanObj_12.setLabUnit("mEq/L");
		medPlanObj_12.setAlertSevereLowRangeSymbol(">");
		medPlanObj_12.setAlertSevereLowRangeValue(1.2);
		medPlanObj_12.setAlertMediumLowRangeSymbol("<");
		medPlanObj_12.setAlertMediumLowRangeValue(0.8);
		medPlanObj_12.setGoalRangeSymbol(">=");
		medPlanObj_12.setGoalRangeValue(0.8);
		medPlanObj_12.setGoalRangeEndSymbol("<=");
		medPlanObj_12.setGoalRangeEndValue(1.2);
		medPlanObj_12.setFrequencyNo("4");
		defaultMedPlan.add(medPlanObj_12);
		
		MedPlan medPlanObj_2=new MedPlan();
		medPlanObj_2.setMonitoringParameter("Systolic");
		medPlanObj_2.setParameterShortName("Systolic BP");
		medPlanObj_2.setLabUnit("mmHg");
		medPlanObj_2.setAlertSevereLowRangeSymbol(">");
		medPlanObj_2.setAlertSevereLowRangeValue(135);
		defaultMedPlan.add(medPlanObj_2);
		
		MedPlan medPlanObj_3=new MedPlan();
		medPlanObj_3.setMonitoringParameter("Diastolic");
		medPlanObj_3.setParameterShortName("Diastolic BP");
		medPlanObj_3.setLabUnit("mmHg");
		medPlanObj_3.setAlertSevereLowRangeSymbol(">");
		medPlanObj_3.setAlertSevereLowRangeValue(85);
		defaultMedPlan.add(medPlanObj_3);
		
		MedPlan medPlanObj_4=new MedPlan();
		medPlanObj_4.setMonitoringParameter("HDLc SerPl-mCnc");
		medPlanObj_4.setParameterShortName("HDL");
		medPlanObj_4.setLabUnit("mg/dL");
		medPlanObj_4.setAlertMediumLowRangeSymbol("<");
		medPlanObj_4.setAlertMediumLowRangeValue(50);
		defaultMedPlan.add(medPlanObj_4);
		
		MedPlan medPlanObj_5=new MedPlan();
		medPlanObj_5.setMonitoringParameter("TSH");
		medPlanObj_5.setParameterShortName("TSH");
		medPlanObj_5.setLabUnit("mIU/L");
		medPlanObj_5.setAlertMediumLowRangeSymbol(">");
		medPlanObj_5.setAlertMediumLowRangeValue(5.5);
		defaultMedPlan.add(medPlanObj_5);
		
		MedPlan medPlanObj_6=new MedPlan();
		medPlanObj_6.setMonitoringParameter("Cr");
		medPlanObj_6.setParameterShortName("Cr");
		medPlanObj_6.setLabUnit("mg/dL");
		medPlanObj_6.setAlertMediumLowRangeSymbol(">");
		medPlanObj_6.setAlertMediumLowRangeValue(1.1);
		defaultMedPlan.add(medPlanObj_6);
		
		MedPlan medPlanObj_7=new MedPlan();
		medPlanObj_7.setMonitoringParameter("Weight");
		medPlanObj_7.setParameterShortName("Body weight");
		medPlanObj_7.setLabUnit("lb");
		defaultMedPlan.add(medPlanObj_7);
		
		MedPlan medPlanObj_8=new MedPlan();
		medPlanObj_8.setMonitoringParameter("Glucose p fast SerPl-mCnc");
		medPlanObj_8.setParameterShortName("FBS");
		medPlanObj_8.setLabUnit("mg/dL");
		medPlanObj_8.setAlertMediumLowRangeSymbol(">");
		medPlanObj_8.setAlertMediumLowRangeValue(100);
		defaultMedPlan.add(medPlanObj_8);
		
			MedPlan medPlanObj_9=new MedPlan();
		medPlanObj_9.setMonitoringParameter("WBC");
		medPlanObj_9.setParameterShortName("WBC");
		medPlanObj_9.setLabUnit(" x 10^3/uL");
		medPlanObj_9.setAlertMediumLowRangeSymbol(">");
		medPlanObj_9.setAlertMediumLowRangeValue(10.9);
		defaultMedPlan.add(medPlanObj_9);
		
			MedPlan medPlanObj_10=new MedPlan();
		medPlanObj_10.setMonitoringParameter("EKG:QTc");
		medPlanObj_10.setParameterShortName("EKG:QTc");
		medPlanObj_10.setLabUnit("msec");
		medPlanObj_10.setAlertSevereLowRangeSymbol(">");
		medPlanObj_10.setAlertSevereLowRangeValue(450);
		medPlanObj_10.setAlertMediumLowRangeSymbol(">=");
		medPlanObj_10.setAlertMediumLowRangeValue(425);
		medPlanObj_10.setAlertMediumHighRangeSymbol("<=");
		medPlanObj_10.setAlertMediumHighRangeValue(450);
		defaultMedPlan.add(medPlanObj_10);
		
		MedPlan medPlanObj_11=new MedPlan();
		medPlanObj_11.setMonitoringParameter("Trigl Bld-mCnc");
		medPlanObj_11.setParameterShortName("Trigl Bld-mCnc");
		medPlanObj_11.setLabUnit("mg/dL");
		medPlanObj_11.setAlertMediumLowRangeSymbol(">");
		medPlanObj_11.setAlertMediumLowRangeValue(150);
		defaultMedPlan.add(medPlanObj_11);
		
		m.setMedPlanDefaultSettings(defaultMedPlan);
end



rule  "Lithium Labs for take action functionality after getting Lab results"
when
	m:PsychopharmMessage(medicine =="lithium",request == Request.LABS)
then
	List<String>psychopharmDefaultLabs=new ArrayList<String>();
	psychopharmDefaultLabs.add("Lithium SerPl-mCnc");
	psychopharmDefaultLabs.add("Lithium SerPl-sCnc");
	m.setResponseList(psychopharmDefaultLabs);
end

rule  "Lithium Labs for take action functionality:Labs Parameters at Step 4 when Lab paramter is Lithium SerPl-mCnc"
when
	m:PsychopharmMessage(medicine =="lithium",request == Request.LABS,monitoring_paramater=="Lithium SerPl-mCnc")
then
	List<MedPlan>defaultMedPlan=new ArrayList<MedPlan>();
	MedPlan medPlanObj_1=new MedPlan();
	medPlanObj_1.setMonitoringParameter("Lithium SerPl-mCnc");
	medPlanObj_1.setParameterShortName("Lithium SerPl-mCnc");
	defaultMedPlan.add(medPlanObj_1);
	m.setMedPlanDefaultSettings(defaultMedPlan);
end

rule  "Lithium Labs for take action functionality:Labs Parameters at Step 4 when Lab paramter is Lithium SerPl-sCnc"
when
	m:PsychopharmMessage(medicine =="lithium",request == Request.LABS,monitoring_paramater=="Lithium SerPl-sCnc")
then
	List<MedPlan>defaultMedPlan=new ArrayList<MedPlan>();
	MedPlan medPlanObj_1=new MedPlan();
	medPlanObj_1.setMonitoringParameter("Lithium SerPl-sCnc");
	medPlanObj_1.setParameterShortName("Lithium SerPl-sCnc");
	defaultMedPlan.add(medPlanObj_1);
	m.setMedPlanDefaultSettings(defaultMedPlan);
end

rule "PHQ-9 questionare for specific question if answered then alert it as severe "
when
	m:PsychopharmMessage(medicine =="lithium",question=="Thoughts that you would be better off dead or hurting yourself in some way",optionsSelected==true)
then
 		ObjectNode page = mapper.createObjectNode();
     	page.put("alertLevel","high");
     	page.put("message","");
     	page.put("recomendationMessage","PHQ-9 Scale: severe depression");
     	m.setResponse(page.toString());
end

rule  "Lithium Cr Labs then return UI value and paramter for CrCl calculation"
when
	m:PsychopharmMessage(medicine =="lithium",request == Request.LABS,monitoring_paramater=="Cr",optionsSelected==true)
then
	m.setResponse(String.valueOf(m.getMonitoring_parameter_value()));
end

rule  "Lithium CrCl Labs then return UI value and paramter for CrCl calculation"
when
	m:PsychopharmMessage(medicine =="lithium",request == Request.CrCl_LABS,monitoring_paramater=="CrCl")
then
	m.setResponseSuccess(true);
end

rule "Lithium dosing guideline first step BMI parameter for Loading BMI value "
when
	m:PsychopharmMessage(medicine =="lithium",request == Request.BMI,monitoring_parameter_value>0)
then
	m.setResponse("BMI");
end

rule "Lithium dosing guideline step 2 for PHQ-9 and Altman Rating scale Lab Paramters"
when
	m:PsychopharmMessage(medicine =="lithium",request == Request.QUESTIONAIRRE_LABS,phq_9 == true)
then
	System.out.println("Lithium dosing guideline step 2 for PHQ-9 and Altman Rating scale Lab Paramters");
	List<String>labResonse=new ArrayList<String>();
	labResonse.add("PHQ-9");
	labResonse.add("Altman Mania Rating Scale");
	m.setResponseList(labResonse);
end
