//created on: Mar 17, 2014
package com.clinakos.rules

//list any import classes here.
import com.clinakos.data.model.rules.Message
import com.clinakos.data.model.rules.Request


//declare any global variables here




rule "Paracetamol-PageList"

    when
        m : Message( medicine == "Paracetamol" , request == Request.PAGE_LIST )
    then
        //actions
        m.setResponse("Diagnosis,Subdiagnosis,Dosage,ActionPlan");

end

rule "Paracetamol-Diagnosis"
    //include attributes such as "salience" here...
    when
        m : Message( medicine == "Paracetamol" , request == Request.DIAGNOSIS )
    then
        //actions
        m.setResponse("Fever");
end

rule "Paracetamol-Subdiagnosis"

	when
		m : Message( medicine == "Paracetamol" , request == Request.SUB_DIAGNOSIS )
	then
		m.setResponse("Fever,Viral Fever,Malaria");
end

rule "Paracetamol-Dosage"

	when
		m : Message( medicine == "Paracetamol" , request == Request.DOSAGE )
	then
		if(m.get("SUB_DIAGNOSIS").equals("Malaria")){
			m.setResponse("500mg");
		}else{
			m.setResponse("100mg");
		}
end

rule "Paracetamol-ActionPlan"

	when
		m : Message( medicine == "Paracetamol" , request == Request.ACTION_PLAN )
	
	then
		if(m.get("SUB_DIAGNOSIS").equals("Malaria")){
			m.setResponse("Go to hospital");
		}else{
			m.setResponse("Take rest");
		}
end
